### ISSUE TITLE
Weird and Complex (toons of switch-case & gotos) Decompilation

### ISSUE THREAD

**Issue by Dentrax** [icsharpcode/ILSpy#1097] opened 2018-03-15 15:07 UTC
I just decompile a Software that made in VB.NET (.NET v4.0.30319). But there were some very strange situations. (dnSpy too) Like: Unnecessary IL_Jumps, Switch-Cases, unsafe codes, needles-casts. I'm uploading it here so you can examine the file what's going on. :)

Please note that: It's not obfuscated.

Download: http://www.mediafire.com/file/pc9vdl7klc6j79z/Issue.rar

ScreenShots:
![a](https://user-images.githubusercontent.com/16493751/37471732-8a368266-287b-11e8-801d-e37060c9af33.png)
![b](https://user-images.githubusercontent.com/16493751/37471733-8a6f9a2e-287b-11e8-8bc0-b77e8a68049c.png)
![c](https://user-images.githubusercontent.com/16493751/37471735-8a93fc66-287b-11e8-8cf9-f84193b01d7e.png)
![d](https://user-images.githubusercontent.com/16493751/37471737-8abd8612-287b-11e8-86b2-fc9779b4deeb.png)

Assembly Info:

```
Scanning -> C:\Users\Furkan\Desktop\Issue\A.exe
File Type : 32-Bit Exe (Subsystem : Win GUI / 2), Size : 115200 (01C200h) Byte(s) | Machine: 0x14C (I386)
Compilation TimeStamp : 0x51B8E019 -> Wed 12th Jun 2013 20:54:49 (GMT)
[TimeStamp] 0x51B8E019 -> Wed 12th Jun 2013 20:54:49 (GMT) | PE Header | - | Offset: 0x00000088 | VA: 0x00400088 | -
[TimeStamp] 0x51B8E019 -> Wed 12th Jun 2013 20:54:49 (GMT) | DebugDirectory | - | Offset: 0x00013004 | VA: 0x00416004 | -
[File Heuristics] -> Flag #1 : 00000100000001001101000000110000 (0x0404D030)
[Entrypoint Section Entropy] : 5.50 (section #0) ".text   " | Size : 0x12A44 (76356) byte(s)
[DllCharacteristics] -> Flag : (0x8540) -> ASLR | DEP | NOSEH | TSA
[SectionCount] 4 (0x4) | ImageSize 0x24000 (147456) byte(s)
[VersionInfo] Company Name : Burak Kalkan
[VersionInfo] Product Name : Security Manager Scanner
[VersionInfo] Product Version : 1.6.27.155
[VersionInfo] File Description : Security Manager Scanner
[VersionInfo] File Version : 1.6.27.155
[VersionInfo] Original FileName : Scanner.exe
[VersionInfo] Internal Name : Scanner.exe
[VersionInfo] Legal Copyrights : Copyright ©  2013
[ModuleReport] [IAT] Modules -> mscoree.dll
[Debug Info] (record 1 of 1) (file offset 0x13000)
Characteristics : 0x0 | TimeDateStamp : 0x51B8E019 (Wed 12th Jun 2013 20:54:49 (GMT)) | MajorVer : 0 / MinorVer : 0 -> (0.0)
Type : 2 (0x2) -> CodeView | Size : 0x78 (120) 
AddressOfRawData : 0x1601C | PointerToRawData : 0x1301C
CvSig : 0x53445352 | SigGuid EF29A6C7-FEC9-407B-BF66BDAFBAB3650C
Age : 0x1 (1) | Pdb : E:\Dosyalar\Projeler\VB.NET\Security_Manager\Security_Manager_Scanner\obj\x86\Debug\Scanner.pdb
[.] .net @ FileOffset 0xDB58 | MetaData->Version 1.1 (struct version) -> v4.0.30319 (net version required)
[.] Flags : 0x0 | Streams : 0x5 (5)  -> #~ | #Strings | #US | #GUID | #Blob
[COR20] MajorRuntimeVersion 0x2 (2) | MinorRuntimeVersion 0x2 (2) -> 0x2.2 (2.2)
[COR20] Flags 0x3
[COR20 Flags] [x] IL_ONLY [x] 32BITREQUIRED [ ] IL_LIBRARY
[COR20 Flags] [ ] STRONGNAME [ ] NATIVE_EP [ ] TRACKDEBUGDATA
[COR20 Flags] [ ] 32BITPREFERRED | 0x0 UNKNOWN
[COR20 Flags] Assembly is NOT strong name signed
[!] File appears to have no protection or is using an unknown protection
- Scan Took : 0.140 Second(s) [00000008Ch (140) tick(s)] [506 of 580 scan(s) done]
```

**Comment by dgrunwald** [comment] 2018-03-17 16:03
1. I just fixed the `array.Length` access. This gets rid of the `unsafe` and simplifies the loop condition to `i < array.Length`.
2. The `checked` is expected here, arithmetic in VB is checked by default.
3. The redundant store to a useless `ex2` variable is really present in the IL code. By default ILSpy tries to represent such useless code in the decompiled C#; but you can enable "Remove dead and side effect free code" in the options.
4. The switch/goto mess here is a case of VB's `On Error Resume Next`. Duplicate of #1092.

**Closed by dgrunwald** 2018-03-17 16:03 UTC
