### ISSUE TITLE
Decompile Xamarin compressed assemblies

### ISSUE THREAD

**Issue by bitk0der** [icsharpcode/ILSpy#2142] opened 2020-09-03 10:13 UTC
Hello, is it possible to decompile compressed Xamarin Assemblies (".dll", NOT ".dll.so")? DLL now can be compressed LZ4 algo, described here: https://github.com/xamarin/xamarin-android/pull/4686

**Comment by dgrunwald** [comment] 2020-09-03 10:17
Duplicate of #2137.

We currently don't plan to work on this feature; but we're happy to accept contributions.

**Comment by christophwille** [comment] 2020-09-08 12:41
Closing duplicate.

**Closed by christophwille** 2020-09-08 12:41 UTC
Labels: Duplicate, Enhancement
