### ISSUE TITLE
Documentation XML is collapsed if no "using"s

### ISSUE THREAD

**Issue by mindless2112** [icsharpcode/ILSpy#891] opened 2017-10-01 03:07 UTC
Normally the initial state of the code view is that the "using"s are collapsed and the documentation XML on the type/member is not collapsed.  If there are no "using"s then the documentation XML is collapsed.  This is unexpected.

ILSpy version 3.0.0.2787

**Comment by siegfriedpammer** [comment] 2017-10-01 09:50
Can you provide an example from a publicly available DLL? So far, I could not reproduce it. Hunting for such a rare case is wasting my time.

**Comment by dgrunwald** [comment] 2017-10-01 14:34
This is probably due to icsharpcode/AvalonEdit#87

**Comment by mindless2112** [comment] 2017-10-01 15:53
[Example](https://github.com/icsharpcode/ILSpy/files/1347274/Example.zip) attached.

**Comment by siegfriedpammer** [comment] 2017-10-16 07:51
This was fixed by the AvalonEdit upgrade in c202b9145bbf2d348594ff570733ae4c5666f400

**Closed by siegfriedpammer** 2017-10-16 07:51 UTC
