### ISSUE TITLE
Delay on new version (8.0P4)

### ISSUE THREAD

**Issue by modz2014** [icsharpcode/ILSpy#2956] opened 2023-04-08 08:21 UTC
The new version of ILSpy there is a delay on loading it not sure why

**Comment by christophwille** [comment] 2023-04-08 08:24
Can you be more specific - on the delay you are seeing and the versions you are comparing.

**Comment by modz2014** [comment] 2023-04-08 08:56
the one before the new one it takes a few seconds to load i notice in the taskbar it loads like 4 in memory before loading ILSpy.exe

**Comment by christophwille** [comment] 2023-04-08 09:01
Are you talking 8.0 p3 to 8.0 p4 or 7 rtm vs 8.0 p4? (or something else) Also, so information about the size of your assembly list as well as the performance of your machine please (win10 or win11 is also relevant).

**Comment by modz2014** [comment] 2023-04-08 09:06
windows 10 8.0 p3 to 8.0 p4

**Comment by siegfriedpammer** [comment] 2023-04-08 23:01
@modz2014 Does my latest commit fix the delay you experience?

**Comment by modz2014** [comment] 2023-04-09 02:21
> @modz2014 Does my latest commit fix the delay you experience?

ill download it and compile it now

**Comment by modz2014** [comment] 2023-04-09 02:21
ill compile it now

**Comment by modz2014** [comment] 2023-04-09 02:37
yes it loads a bit better only like 1 second delay not as bad as it was before

**Comment by christophwille** [comment] 2023-04-09 07:59
For documentation purposes: root cause analysis information in comments following https://github.com/icsharpcode/ILSpy/pull/2906#issuecomment-1500981661

**Comment by christophwille** [comment] 2023-04-10 08:16
@modz2014 if you want to measure (roughly) startup time, you can place

```
var diff = DateTime.Now - Process.GetCurrentProcess().StartTime;
MessageBox.Show(diff.ToString());
```

in `MainWindow.OpenAssemblies`. On @siegfriedpammer's machine that is roughly 1.26 seconds, with no discernible difference for P3 to P4 now after the fix. Closing the issue.

**Closed by christophwille** 2023-04-10 08:16 UTC
Labels: Bug, UI, Performance

**Comment by modz2014** [comment] 2023-04-10 08:32
no worries cheers
