### ISSUE TITLE
VB.NET On Error statement not detected

### ISSUE THREAD

**Issue by jcarrenopayall** [icsharpcode/ILSpy#2388] opened 2021-05-03 22:34 UTC
when decompiling dll, this type of error appears in some class modules generating  incorrect code:

//Discarded unreachable code: IL_0030, IL_0032, IL_0048, IL_006c

here an example in this case:

private DateTime GetFirstApplyDate(ref DateTime piStartDTDate)
		{
			//Discarded unreachable code: IL_0030, IL_0032, IL_0048, IL_006c
			int num = default(int);
			DateTime result;
			int num2 = default(int);
			try
			{
				ProjectData.ClearProjectError();
				num = 2;
				clsBCDateTimeCalculator clsBCDateTimeCalculator2 = mBCDateTimeCalculator;
				DateTime pioBeginningDate = default(DateTime);
				DateTime pioEndingDate = default(DateTime);
				GetBeginAndEndPeriodDatesFromDate(ref piStartDTDate, ref pioBeginningDate, ref pioEndingDate);
				DateTime piDTDate = pioBeginningDate;
				int piNumberToAdd = mApplyDays;
				bool piBlnIncludeFirstPeriod = true;
				result = clsBCDateTimeCalculator.CalculateDateGivenDays(piDTDate, piNumberToAdd,   piBlnIncludeFirstPeriod);
				clsBCDateTimeCalculator2 = null;
			}
			catch (object obj) when (obj is Exception && num != 0 && num2 == 0)
			{
				ProjectData.SetProjectError((Exception)obj);
				/*Error near IL_006a: Could not find block for branch target IL_0032*/;
			}
			if (num2 != 0)
			{
				ProjectData.ClearProjectError();
			}
			return result;
		}

**Comment by dgrunwald** [comment] 2021-05-04 12:09
ILSpy can't handle the jump from the catch block back into the try block.
I think these are generated by VB.NET when using `On Error Resume Next`.

**Comment by siegfriedpammer** [comment] 2021-05-08 12:43
Duplicate of #1092.

**Comment by dgrunwald** [comment] 2021-05-27 17:12
But #1092 was also closed.
I think we should keep at least one issue on this topic open.

There is a potential solution of how to decompile this in C#:
We could introduce a variable `int where_to_enter_try;` that gets set directly before the `try {` block; also gets set before every branch back into the try-block, and then we emit a `switch` at the beginning of the try-block that inspects this variable and executes a `goto` accordingly. The end result will be horribly mangled control-flow (the graph in https://github.com/icsharpcode/ILSpy/issues/1361#issuecomment-515232688 lets you know what to expect), but at least it'll recompile with the same semantics.

**Closed** 2021-11-28 19:37 UTC
Labels: Bug, Decompiler
