### ISSUE TITLE
ValueTuple.ToString seriously confusing decompiler

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1921] opened 2020-01-30 08:14 UTC
This might already be on the bullet list of "things to do", but it could serve as a concrete test case.

- Open from GAC
- mscorlib 4.0.0.0
- ValueTuple&lt;T1&gt;

Decompile its `ToString`. :-)

Also applies to its `IValueTupleInternal.ToStringEnd`.

**Comment by siegfriedpammer** [comment] 2020-01-30 11:09
Input is:

```csharp
using System;
public class C<T> {

    T item;

    public override string ToString()
    {
        return "(" + item?.ToString() + ")";
    }

}
```

**Comment by siegfriedpammer** [comment] 2020-01-30 11:11
Looks like a duplicate of #1050

**Comment by tamlin-mike** [comment] 2020-01-30 11:47
It indeed seems to be the same problem. Closing this and adding a comment to #1050.

**Closed** 2020-01-30 11:47 UTC
