### ISSUE TITLE
ILSpy_binaries_6.0.0.5671-preview3 crashfest

### ISSUE THREAD

**Issue by Csimbi** [icsharpcode/ILSpy#1995] opened 2020-04-29 15:04 UTC
Hello,
I downloaded this build just now: ILSpy_binaries_6.0.0.5671-preview3
Having started it (just started it, no assemblies are open) , the 'Debug Steps' bar is visible on the left.
Clicking the 'Assemblies' button below, or by simply closing the 'Debug Steps' using the little 'x' in the corner, ILSpy turns into a crashfest.
Dialogs over dialogs over dialogs over dialogs over dialogs over dialogs are popping up with walls of exception text.
I try closing them, but new ones pop every time.
I have to end the process via the task manager.
Preview 2 was fine.

Anyone else having the same issue?
What do you need from me to track down the problem?
Thanks!

**Comment by siegfriedpammer** [comment] 2020-04-29 15:19
This is very unfortunate! Can you try posting some of these exceptions?

You could try creating a backup of your ILSpy.xml (located in %APPDATA%\ICSharpCode) and then deleting it.

**Comment by Csimbi** [comment] 2020-04-29 18:11
Sure!
It keeps blinking and contents change, but I snatched a screenshot anyway, please find it attached.

![ILSpy_crash](https://user-images.githubusercontent.com/5107288/80631057-7bacd900-8a55-11ea-8604-f0ce0c0c660a.png)

You were spot on with the XML file.
I deleted it and all issues are now solved.
However, I'd prefer if a simple XML file would not cause a crash ;-)

Thank you!

**Comment by siegfriedpammer** [comment] 2020-04-29 19:00
Do you still have the old XML file? If so, I would like to try to reproduce the problem on my machine...

I think it should suffice, if you post the `<DockLayout>` part of that file.

Thank you very much!

**Comment by Csimbi** [comment] 2020-04-29 22:35
I do, here you are.
[ILSpy.zip](https://github.com/icsharpcode/ILSpy/files/4555120/ILSpy.zip)

**Comment by siegfriedpammer** [comment] 2020-04-30 05:40
Thank you very much for getting back to me. Unfortunately I cannot reproduce the crash using that file. Without a stack trace it is impossible for me to add additional error handling. Not sure how we should proceed...

**Comment by Csimbi** [comment] 2020-04-30 09:52
So how do I get a stack trace?

**Comment by siegfriedpammer** [comment] 2020-04-30 13:28
Could you try downloading a debug build of ILSpy and starting it with the VS debugger attached? You can get a debug build from here: https://ci.appveyor.com/project/icsharpcode/ilspy/builds/32549837/job/gxb82e2581b2i4aa/artifacts

Thank you!

**Comment by Csimbi** [comment] 2020-04-30 15:06
I could not find a debug build for 6.0.0.5671.
With 6.0.0.5701 it does not happen anymore.
Maybe it was fixed already?

**Comment by christophwille** [comment] 2020-04-30 15:10
https://ci.appveyor.com/project/icsharpcode/ilspy/builds/32219008/job/kh5924p45jgkdbcn/artifacts

**Comment by siegfriedpammer** [comment] 2020-04-30 15:18
> Maybe it was fixed already?

I am not aware of any recent changes related to the UI components that might have fixed the problem.

**Comment by Csimbi** [comment] 2020-05-01 07:43
I tried the 6.0.0.5671 debug package that christophwille linked.
That does not crash, either.
When I put back the non-debug build from ILSpy_binaries_6.0.0.5671-preview3.zip, it produces the problem again, 100% or the time.
Weird.

**Comment by siegfriedpammer** [comment] 2020-05-01 09:53
Looking at your screenshot: I have removed the (debug-only) debug steps pad from the release build configuration completely. Previously it was present in the list of registered pad, but actually not functional. It should now be properly ignored when restoring the previous layout.

I hope this fixes the problem.

**Comment by christophwille** [comment] 2020-05-02 08:17
@Csimbi could you try the release binaries https://ci.appveyor.com/project/icsharpcode/ilspy/build/job/mexqvy7a293g3myq/artifacts to see if the crash still happens for release?

**Comment by Csimbi** [comment] 2020-05-02 08:36
@Christoph
I tried the the release binaries 6.0.0.5733 linked above.
No problems whatsoever.

**Comment by christophwille** [comment] 2020-05-02 08:38
ok, so Siegi's commit did fix the problem. Closing.

**Closed by christophwille** 2020-05-02 08:38 UTC
Labels: UI
