### ISSUE TITLE
Analyser - Used By not finding interface usage

### ISSUE THREAD

**Issue by slaneyrw** [icsharpcode/ILSpy#648] opened 2015-10-19 01:38 UTC
I'm decompiling the ASP.NET Identity bits for version 2,
in particular Microsoft.AspNet.Identity.Core and Microsoft.AspNet.Identity.EntityFramework.

If I try to find usages of **`Microsoft.AspNet.Identity.EntityFramework.UserStore<TUser, TRole, TUserLogin, TUserRole, TUserClaim>.GetClaimsAsync(TUser)`** the analyzer returns no matches.

But If I do the same from interface that this class implements **`Microsoft.AspNet.Identity.IUserStore<TUser, TRole, TUserLogin, TUserRole, TUserClaim>.GetClaimsAsync(TUser)`** the analyzer correctly finds a call from **`Microsoft.AspNet.Identity.UserManager<TUser, TKey>.GetClaimsAsync(TKey)`**

This maybe the worst-case scenario where async/await, open generic inheritance and cross assembly facets are involved, but I would expect the usage to be located from the UserStore method by UserManager.

**Comment by weltkante** [comment] 2015-10-20 09:03
Thats the expected behavior I'd say, because nobody calls the concrete implementation of the UserStore but only calls the interface. Sometimes its actually useful to be able to differentiate between these, but most often probably not. The analyzer probably needs to become smarter and/or get more options.

**Comment by siegfriedpammer** [comment] 2019-10-10 09:26
Closing this as "by design"... if you want interface uses, you can use the "implemented by" analyzer on the interface method definition.

**Closed by siegfriedpammer** 2019-10-10 09:26 UTC
Labels: Analyzer

**Comment by weltkante** [comment] 2019-10-10 10:56
> if you want interface uses, you can use the "implemented by" analyzer

That won't find callers of the interface you are implementing, you have to run "used by" on the method on the interface. Its unfortunate that the analyzers aren't smarter and assist you here, but at least you can work around it.

**Comment by siegfriedpammer** [comment] 2019-10-10 11:09
Contributions in this area are welcome!
