### ISSUE TITLE
No events? (WinForms InitializeComponents)

### ISSUE THREAD

**Issue by chrisstophersaur** [icsharpcode/ILSpy#1180] opened 2018-06-16 01:45 UTC
Every time I decompile a program and load it up in visual studios 2017 all the events are empty, for example if their is a button1 and you click it it will make a button1_click_1 instead of using the code button1_click. This happens for every single item. Someone please help me.

**Comment by chrisstophersaur** [comment] 2018-06-16 08:50
Alrighty, thanks for the quick reply and hopefully you guys can figure it out.

**Comment by siegfriedpammer** [comment] 2018-06-16 15:42
The problem is that the Forms Designer expects events to use explicit method group converssions. That is, it expects `button1.Click += new EventHandler(button1_Click);` instead of `button1.Click += button1_Click;`. This can be fixed by setting `DecompilerSettings.UseImplicitMethodGroupConversion` to `false`. The default value is `true`. Unfortunately, this setting cannot be modified from within ILSpy. (If you use the latest build from the build server, it can be turned off, if you switch to C# 1.0, but that is not a very good fix for this problem.)

**Comment by kant2002** [comment] 2018-06-16 18:27
The usual problem with decompilation of Windows Forms is that it produce approximate following problems:
- BeginInit/EndInit should be written with explicit conversion which does not make sense for the ILSpy. And for me as well, since most controls have BeginInit/EndInit methods
- Enumeration serialization inside InitializeComponent should always use fully qualified name
- If Resources used, that provide additional burden for decompilation.

All these rules should be strictly followed, otherwise Windows Forms designer would not recognize most of the modifications. If @siegfriedpammer think such decompilation is worth to have in the ILSpy I could take a look at this.

**Comment by christophwille** [comment] 2018-06-17 05:04
Given that Windows Forms will get another lease of life (netcore3) it might be a good idea to consider this.

**Comment by AraHaan** [comment] 2018-08-07 16:30
Also you plan to have it where the form designer code would output in it's own ``<form name>.Designer.cs/vb``?

**Closed** 2019-03-08 22:06 UTC

**Comment by siegfriedpammer** [comment] 2019-03-08 22:08
Currently we have no plans to include support for generating `partial` classes and moving the InitializeComponent method + control member declarations to a separate file.

**Comment by AraHaan** [comment] 2019-03-13 18:14
I see, My idea was to check if the class inherits from ``System.Windows.Form.Form`` and then set that ``IsWinForms`` to true; on top of that method if you see the entire code body by clicking on the class itself and not the specific method / member in the form / control.
