### ISSUE TITLE
PNG Transparency 

### ISSUE THREAD

**Issue by HajnyPL** [icsharpcode/ILSpy#1019] opened 2018-01-03 17:32 UTC
When I open osu!ui.dll and preview (or save) images, and then it doesn't save the transparency and in the game its fine! Please fix this

**Comment by siegfriedpammer** [comment] 2018-01-03 19:28
I just tried this with the transparent PNGs included in ILSpy.exe and could not reproduce the problem. It would help if you could provide the assembly in question for investigation, otherwise this is not fixable.

**Comment by christophwille** [comment] 2018-01-23 18:18
No further information has been provided, closing.

**Closed by christophwille** 2018-01-23 18:18 UTC
