### ISSUE TITLE
Search bar crash

### ISSUE THREAD

**Issue by RimpelF** [icsharpcode/ILSpy#701] opened 2016-04-25 11:03 UTC
Just updated to the latest version today, in the search field I enter 'm:' then entering the first char of the method and it crashes From eventvwr:

Application: ILSpy.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
Stack:
   at ICSharpCode.ILSpy.AbstractSearchStrategy.IsMatch(System.String)
   at ICSharpCode.ILSpy.AbstractSearchStrategy.Add[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, Mono.Cecil.TypeDefinition, ICSharpCode.ILSpy.Language, System.Action`1<ICSharpCode.ILSpy.SearchResult>, System.Func`2<System.__Canon,Boolean>, System.Func`2<System.__Canon,System.Windows.Media.ImageSource>)
   at ICSharpCode.ILSpy.AbstractSearchStrategy.Search(Mono.Cecil.TypeDefinition, ICSharpCode.ILSpy.Language, System.Action`1<ICSharpCode.ILSpy.SearchResult>)
   at ICSharpCode.ILSpy.SearchPane+RunningSearch.Run()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

rgds

**Comment by siegfriedpammer** [comment] 2016-04-25 11:18
I tried to reproduce this, but could not so far. Can you provide more information on this?

**Comment by neolithos** [comment] 2016-04-25 14:35
Duplicate of #692.

**Comment by siegfriedpammer** [comment] 2016-04-26 04:41
Try updating to the latest nightly from http://build.sharpdevelop.net/BuildArtefacts/#ILSpyMaster and tell us if the problem persists. If so, the issue can be reopened.

**Closed by siegfriedpammer** 2016-04-26 04:41 UTC
