### ISSUE TITLE
Code color theme like VS2019 normal

### ISSUE THREAD

**Issue by ahdung** [icsharpcode/ILSpy#2206] opened 2020-11-04 06:09 UTC
I like this one:
![image](https://user-images.githubusercontent.com/12094247/98075406-4a4f1300-1ea7-11eb-906e-53f31b2311d3.png)

**Comment by christophwille** [comment] 2020-11-04 06:23
Duplicate of https://github.com/icsharpcode/ILSpy/issues/534

**Closed by christophwille** 2020-11-04 06:23 UTC
Labels: Enhancement
