### ISSUE TITLE
Rename source variables

### ISSUE THREAD

**Issue by BoltBait** [icsharpcode/ILSpy#731] opened 2016-07-11 01:40 UTC
When ILSpy decompiles something it always creates variables named: num, num1, num2, etc.

I'd like to be able to click on one of those variable names and press F2 and rename the variable.  The variable name would be updated everywhere on the screen.  (For my purposes, it would not be necessary to remember that rename beyond the current session.)

Of course, it would have to check for collisions before allowing the rename.

The reasoning for this is that as I start to understand the function of the various variables I could rename them and get a better understanding of the overall code.

**Comment by exyi** [comment] 2016-07-11 08:26
I also needed this feature, so I have coded it :). Have a look at my fork https://github.com/exyi/ilspy at master. It makes the parts of textview where the variables are editable. But it is probably a bit unstable, so I have not made a PR.

**Comment by dgrunwald** [comment] 2018-06-02 15:45
Duplicate of #209

**Closed by dgrunwald** 2018-06-02 15:45 UTC
Labels: New Feature, UI
