### ISSUE TITLE
Wrong path for System.Data reference in DirectWriteForwarder.dll (WPF)?

### ISSUE THREAD

**Issue by rohahn** [icsharpcode/ILSpy#3128] opened 2023-11-23 16:01 UTC
### Steps to reproduce
1. Open DirectWriteForwarder.dll (e.g. `C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.25\DirectWriteForwarder.dll`)
2. Select References / System.Data
3. Check the path in the detail view

![image](https://github.com/icsharpcode/ILSpy/assets/9958641/04de13cc-22a0-4a89-b266-71e16dcf9d02)

Although the requested version is 4.0.0.0, the version from .NET 6 is used.

JetBrains dotPeek shows the .NET Framework 4.x version.

![image](https://github.com/icsharpcode/ILSpy/assets/9958641/995954e1-9eaa-4942-85aa-32134e7920ed)

The `System.Data` assembly that is installed by .NET 6 or newer contains references that cannot be resolved:

![image](https://github.com/icsharpcode/ILSpy/assets/9958641/38d4753e-1e96-4c8e-9b50-990e3fc14e00)

### Details
* Product in use: ILSpy  / ICSharpCode.Decompiler
* Version in use: 8.2.0.7535

We noticed this issue when analyzing a [Docfx problem](https://github.com/dotnet/docfx/issues/9459).
DirectWriteForwarder.dll is referenced by PresentationCore.dll of WPF.

When debugging a WPF application I noticed that `System.Data.dll` is not loaded at all, although `DirectWriteForwarder.dll` is loaded.

Therefore I am not really sure what is the correct behavior here. Either ILSpy/Decompiler should resolve `System.Data 4.0.0.0` in `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Data.dll` or it should be able to resolve the Version 0.0.0.0 references in `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.25\System.Data.dll`.

Any ideas?

**Comment by siegfriedpammer** [comment] 2024-10-19 10:23
I would argue that dotPeek is actually doing the wrong thing, because many of the framework assemblies in frameworks .NET 5 or newer still use the 4.0.0.0 version numbers in their assembly manifests. The correct thing is to load the System.Data, Version=4.0.0.0 from the .NET 6.0 framework directory. Despite disguising themselves as 4.0 version assemblies, these assemblies usually contain type forwarders and sometimes new types which are not available in older frameworks. The version number is actually wrong/misleading, but that's the mess we're living in for the sake of eternal backwards compatibility. The assembly resolving logic in ILSpy and the decompiler engine has a lot of special cases and hacks because of this mess.

**Comment by siegfriedpammer** [comment] 2024-10-19 15:08
> or it should be able to resolve the Version 0.0.0.0 references in `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.25\System.Data.dll`.

That is exactly what ILSpy does, if you run the "Load Dependencies" context menu command on System.Data.dll of .NET 6.0 in ILSpy. I believe the problem you experience comes from incorrectly using/configuring UniversalAssemblyResolver inside docfx.

**Comment by siegfriedpammer** [comment] 2024-10-24 06:11
Closing - works as designed.

**Closed** 2024-10-24 06:11 UTC
Labels: Bug
