### ISSUE TITLE
Cannot implicitly convert type 'int' to 'XXXX'

### ISSUE THREAD

**Issue by blamara** [icsharpcode/ILSpy#590] opened 2015-04-06 16:52 UTC
when we have simple code as following:

```
public byte GetValue(byte a, byte b)
{
  byte x = (byte)(a - b);
  return x;
}

public ushort GetValue(ushort a, ushort b)
{
  ushort x = (ushort)(a - b);
  return x;
}
```

IL v2.3 ommits explicite casting in decompiled code, which results in compiler error CS0266.

```
// error CS0266: Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
//public byte GetValue(byte a, byte b)
//{
//  return a - b;
//}

// error CS0266: Cannot implicitly convert type 'int' to 'ushort'. An explicit conversion exists (are you missing a cast?)
//public ushort GetValue(ushort a, ushort b)
//{
//  return a - b;
//}
```

Guess there are more types that would result in same error, because of math subtract coercion to int as result.

There for explicit cast must be applied before setting (returning) value.

**Comment by 0xd4d** [comment] 2015-04-06 18:13
Similar to #572

**Comment by SilverNexus** [comment] 2015-07-14 19:25
I think the issue is more than just return values. Any assignment to a smaller-than-32-bit integer that involves a mathematical operation in the assignment is affected.
When using VS2013 (at minimum, haven't tested other versions), mathematical operations (+, -, /, *, maybe more) between two 16- or 8-bit integers (byte, sbyte, short, or ushort) create a 32-bit integer result.

With C#'s strict typecasting system, it becomes a royal pain to go back and manually cast variables in a large project.

**Comment by dgrunwald** [comment] 2016-12-03 23:08
Fixed on the newdecompiler branch.

**Closed by dgrunwald** 2016-12-03 23:08 UTC
