### ISSUE TITLE
what is it this error

### ISSUE THREAD

**Issue by chinazhangbo** [icsharpcode/ILSpy#2631] opened 2022-02-11 06:42 UTC
![1644560849(1)](https://user-images.githubusercontent.com/15043659/153547756-3dec6e5c-ca5d-4b11-bddc-bf72ffe50c12.png)

**Comment by christophwille** [comment] 2022-02-11 06:56
Duplicate of #2623 as well as #2627. Please do check other bug reports first, we actually intentionally kept #2627 open.

**Closed** 2022-02-11 14:59 UTC
Labels: Bug, Duplicate
