### ISSUE TITLE
Decompiled enums without `[Flags]` could have their values displayed in hex form

### ISSUE THREAD

**Issue by AlFasGD** [icsharpcode/ILSpy#2618] opened 2022-01-26 18:58 UTC
Copy-pasted from dotnet/roslyn#59056

**Steps to Reproduce**:

1. Choose to view the decompiled source of an enum in `System` that does not have the `[Flags]` attribute
2. Ensure that it has enough values to exceed 16

**Expected Behavior**:
The values are consistently displayed in decimal representation.

**Actual Behavior**:
Some values are displayed in hexadecimal representation, as if they could represent flags.

**Additional Information**:
This bug could be related to ILSpy. It has also appeared on enums contained in `Microsoft.CodeAnalysis`, meaning it could not be restricted to `System` enums.

**Screenshot**:
In the `System.TypeCode` enum, the values 15 and 16 are displayed in hex form as if they could represent flags:
![Some values in TypeCode are in hex representation](https://user-images.githubusercontent.com/8298332/151030531-07f649cb-19d9-498f-9cfc-47126103d65b.png)

**Comment by siegfriedpammer** [comment] 2022-01-26 19:17
Duplicate of #2448

**Closed by siegfriedpammer** 2022-01-26 19:17 UTC
Labels: Bug
