### ISSUE TITLE
.net lower 7.0: Ref locals is not supported

### ISSUE THREAD

**Issue by asdMild** [icsharpcode/ILSpy#1106] opened 2018-03-30 06:42 UTC
i chose the latest version of the ILSpy,
and chose the c#5.0,
but there are some ref locals find in the reflect project.
the ref locals is add to c# in new c# 7.0,
it error in c# 5.0
![default](https://user-images.githubusercontent.com/20412251/38127338-59fd008a-3428-11e8-9ebe-a1b7a41afbab.PNG)

**Comment by siegfriedpammer** [comment] 2018-03-30 06:45
Duplicate of #1082: See the comments for an explanation of why this is currently expected behavior.

**Closed by siegfriedpammer** 2018-03-30 06:45 UTC
