### ISSUE TITLE
dynamic issue

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2219] opened 2020-11-14 10:55 UTC
[1.zip](https://github.com/icsharpcode/ILSpy/files/5540533/1.zip)
1. Reflection.GetArenaDeckInternal():
```C#
	Type typeFromHandle = typeof(RewardDataParser);
	val2 = service["m_chest"];
	dynamic val6;
	if ((object)val2 == null)
	{
		val6 = null;
	}
	else
	{
		dynamic val3 = val2["<Rewards>k__BackingField"];
		val6 = (((object)val3 != null) ? val3["_items"] : null);
	}
	arenaInfo.Rewards = typeFromHandle.Parse(val6); //error, should RewardDataParser.Parse(..)???
```
`System.Type` doesn't contain a `Parse` method, but `RewardDataParser` contain a `Parse` method, should use `RewardDataParser.Parse` instead it?

2. Reflection.GetMedalInfoInternal:
```
	return new MedalInfo
	{
		Standard = <GetMedalInfoInternal>g__GetMedalInfoData|23_0(source),
		Wild = <GetMedalInfoInternal>g__GetMedalInfoData|23_0(source2)
	};
```

```<GetMedalInfoInternal>g__GetMedalInfoData|23_0``` is a CompilerGenerated method, should inline its codes?

**Comment by siegfriedpammer** [comment] 2020-11-14 20:39
ad 1) if you change the language settings >= C# 6.0 it can be decompiled properly. Will take a look at fixing this on lower language settings.
ad 2) these are local functions, you must use at least C# 7.0 for this to be decompiled correctly.

**Comment by CreateAndInject** [comment] 2020-11-15 09:36
`dynamic` is a new feature in C# 4.0, is there any change from C# 6.0?

**Comment by siegfriedpammer** [comment] 2020-11-15 10:43
The problem is that the code uses the "null-forgiving" operator `?[]`, which is a feature of C# 6. Not using the operator makes it necessary to keep the explicit control flow (if statements), which prevents inlining.

```csharp
private static ArenaInfo GetArenaDeckInternal()
{
	dynamic service = GetService("DraftManager");
	if (service == null)
	{
		return null;
	}
	dynamic val = Reflection.GetDeck(service["m_draftDeck"]);
	if (val == null)
	{
		return null;
	}
	dynamic val2 = service["m_currentSeason"]?["_Season"]?["<GameContentSeason>k__BackingField"]?["<SeasonId>k__BackingField"]; // here
	ArenaInfo arenaInfo = new ArenaInfo();
	arenaInfo.Wins = service["m_wins"];
	arenaInfo.Losses = service["m_losses"];
	arenaInfo.CurrentSlot = service["m_currentSlot"];
	arenaInfo.Deck = val;
	arenaInfo.Rewards = RewardDataParser.Parse(service["m_chest"]?["<Rewards>k__BackingField"]?["_items"]);
	arenaInfo.Season = val2;
	return arenaInfo;
}
```

Fixing this, would require some form of copy-propagation, however, copy-propagation has had a lot of negative effects on other parts of the decompiler by breaking some patterns, so we try to avoid it.

**Comment by siegfriedpammer** [comment] 2021-11-13 12:16
Closing this. Please use the appropriate language version when decompiling assemblies.

**Closed by siegfriedpammer** 2021-11-13 12:16 UTC
Labels: Bug, Decompiler
