### ISSUE TITLE
5.0 preview1 crash

### ISSUE THREAD

**Issue by Csimbi** [icsharpcode/ILSpy#1475] opened 2019-04-03 11:24 UTC
Hello,
While saving the source, I get a popup saying:
"A new guard page for the stack cannot be created."
Clicking OK causes ILSpy to disappear.
Any tips?
Thank you!

**Comment by siegfriedpammer** [comment] 2019-04-03 12:02
Would it be possible for you to provide the assembly, so I can investigate this? Thank you very much!

**Comment by Csimbi** [comment] 2019-04-03 12:34
Hello,
I am not sure I allowed to distributed them - there are quite a few DLLs.
It's basically BattleTech FlashPoint (1.50) with the RougeTech mod
installed (which patches Assembly-CSharp.dll).

**Comment by siegfriedpammer** [comment] 2019-04-03 12:35
Please send an email to siegfried.pammer@gmail.com.

**Comment by siegfriedpammer** [comment] 2019-04-11 12:35
The problem is that the builds created by appveyor do not have the stack extension. `editbin.exe` is missing in the appveyor image. @dgrunwald @christophwille Do you have any idea how we could get this working again?

**Comment by siegfriedpammer** [comment] 2019-04-11 15:13
Should be fixed in 652d0bf6eed3089b049b6c00d7c2aa21dbbd8cfa. @Csimbi please confirm. Thank you!

**Closed** 2019-04-11 17:34 UTC
