### ISSUE TITLE
ambiguous

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1161] opened 2018-06-03 15:41 UTC
original code:
```
using System;
using ns1;
using ns2;

namespace ns1
{
    class Test : Attribute
    {
    }
}
namespace ns2
{
    class TestAttribute : Attribute
    {
    }
}
namespace ns3
{
    class Program
    {
        [ns1.Test]
        static void Main(string[] args)
        {
            typeof(Test).ToString();
            typeof(TestAttribute).ToString();
        }
    }
}
```
deompilation code:
```
using ns1;
using ns2;

namespace ns3
{
	internal class Program
	{
		[Test]
		private static void Main(string[] args)
		{
			typeof(Test).ToString();
			typeof(TestAttribute).ToString();
		}
	}
}
```
'Test' is ambiguous between 'Test' and 'TestAttribute'

**Comment by siegfriedpammer** [comment] 2018-06-06 11:01
Duplicate of #1149

**Closed by siegfriedpammer** 2018-06-06 11:01 UTC
