### ISSUE TITLE
v.4.rc1: IndexOutOfRangeException in Decompiler.IL.Transforms.TransformArrayInitializers.HandleSimpleArrayInitializer

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1380] opened 2019-01-06 10:09 UTC
ILSpy version 4.0.0.4509-rc1

```
Error decompiling System.Data.Odbc.OdbcConnectionStringBuilder..cctor
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ICSharpCode.Decompiler.IL.Transforms.TransformArrayInitializers.HandleSimpleArrayInitializer(ILFunction function, Block block, Int32 pos, ILVariable store, IType elementType, Int32[] arrayLength, ValueTuple`2[]& values, Int32& elementCount) in offset 0
   at ICSharpCode.Decompiler.IL.Transforms.TransformArrayInitializers.DoTransform(ILFunction function, Block body, Int32 pos) in offset 201
   at ICSharpCode.Decompiler.IL.Transforms.TransformArrayInitializers.ICSharpCode.Decompiler.IL.Transforms.IStatementTransform.Run(Block block, Int32 pos, StatementTransformContext context) in offset 14
   at ICSharpCode.Decompiler.IL.Transforms.StatementTransform.Run(Block block, BlockTransformContext context) in offset 98
   at ICSharpCode.Decompiler.IL.Block.RunTransforms(IEnumerable`1 transforms, BlockTransformContext context) in offset 38
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in offset 121
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.Run(ILFunction function, ILTransformContext context) in offset 122
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 520
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 942
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 191
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IList`1 definitions) in offset 370
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(IMethod method, ITextOutput output, DecompilationOptions options) in offset 170
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in offset 61
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass34_0.<DecompileAsync>b__0() in offset 36
```

target:

// C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
// System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Global type: <Module>
// Architecture: x86
// This assembly contains unmanaged code.
// Runtime: v4.0.30319
// This assembly is signed with a strong name key.
// Hash algorithm: SHA1
// Public key: 0000000040000000

**Comment by siegfriedpammer** [comment] 2019-01-06 10:11
possible duplicate of #1377

**Comment by siegfriedpammer** [comment] 2019-01-06 10:18
Verified.

**Closed by siegfriedpammer** 2019-01-06 10:18 UTC
