### ISSUE TITLE
Property with parameters (retry)

### ISSUE THREAD

**Issue by FVillaf** [icsharpcode/ILSpy#1560] opened 2019-07-03 19:54 UTC
![Issue1](https://user-images.githubusercontent.com/7819035/60620680-3dea1000-9db2-11e9-84c9-b8da7efabae0.png)

The previous code represents a **"Property with parameters"**, something not supported (actually) by C# compiler (VB yes)

ILSpy incorrectly decompile the sample code as:

`public virtual LNKPCJLANAO AHANCLBKKID => (LNKPCJLANAO)MIABODPHOIP[EHJNMODJEAN];
`

which is wrong, because the arg (EHJNMODJEAN) is not defined in any place. 

There are previous issues about this, but they are old and still unfixed. Is possible to fix ILSpy to emit a method in this case, warning user about the unsupported feature?

**Comment by siegfriedpammer** [comment] 2019-07-13 18:47
> Is possible to fix ILSpy to emit a method in this case, warning user about the unsupported feature?

As noted in #1089: All uses of the property would have to directly use the accessor methods. However, it would be impossible to decompile declarations of parameterized properties.

Currently we have no plans to add this feature, but contributions are very welcome! If anyone is interested in implementing this feature, please feel free to ask any questions regarding the implementation.

**Comment by siegfriedpammer** [comment] 2019-08-10 22:00
Closing because this is essentially is a duplicate of #1089.

**Closed by siegfriedpammer** 2019-08-10 22:00 UTC
Labels: C#, Decompiler, Duplicate, Enhancement
