### ISSUE TITLE
ILSpy incorrectly shows every assembly referencing mscorlib

### ISSUE THREAD

**Issue by davidfowl** [icsharpcode/ILSpy#435] opened 2013-11-27 04:42 UTC
### Repro Steps

- Create a class with the following content:

```
namespace ClassLibrary1
{
    public class Class1
    {
    }
}
```
- Run the following command line:

```
csc /target:library /nostdlib /noconfig Class1.cs /r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Runtime.dll"
```
The above assumes you have the reference assemblies for .NETCore.

Open in ilspy and look at the references for Class1.dll and observe the mscorlib reference:

![image](https://f.cloud.github.com/assets/95136/1628733/10479a2c-571e-11e3-8a30-5c908b182e00.png)

**Comment by 0xd4d** [comment] 2015-01-29 02:31
It's Mono.Cecil that adds a mscorlib reference when there's none. ILSpy just uses the values Mono.Cecil hands over to it.

**Comment by davidfowl** [comment] 2015-01-29 12:17
So you're saying that I should file a bug on Cecil because that's what ILSpy decided to use?

**Comment by siegfriedpammer** [comment] 2015-02-24 22:27
@davidfowl sorry for my late response... which version of ILSpy did you use? I tried to reproduce the problem using the steps provided, but the references are read correctly using the latest version.

**Comment by davidfowl** [comment] 2015-02-24 22:34
I'll try the latest and see if it repros

**Comment by siegfriedpammer** [comment] 2015-03-01 07:59
@davidfowl any updates on this?

**Comment by siegfriedpammer** [comment] 2015-03-05 15:23
Closing this, because it is no longer reproducible.

**Closed by siegfriedpammer** 2015-03-05 15:23 UTC
