### ISSUE TITLE
ilspycmd gives strange filenames on macOS

### ISSUE THREAD

**Issue by wjk** [icsharpcode/ILSpy#2420] opened 2021-05-25 19:06 UTC
### Steps to reproduce

I am running `ilspycmd -p -o . Windows.Win32.md` on macOS Big Sur 11.3. The decompilation succeeds, but the resulting directories contain backslashes between the namespace names (see screenshot). I would appreciate it if this could be fixed to either emit forward slashes, or dots. (Attempting to fix the problem using `sed` and `mv` only exacerbated the problem by seemingly deleting namespaces at random.)

[This is the file I am using when I see this problem.](https://github.com/microsoft/windows-rs/raw/master/crates/gen/default/Windows.Win32.winmd)

### Error message shown

![Screenshot](https://user-images.githubusercontent.com/1915951/119554174-60042700-bd6a-11eb-87d0-94d9f338b805.png)

### Details
* Product in use: ilspycmd dotnet global tool
* Version in use: 7.0.0.6488

**Comment by christophwille** [comment] 2021-05-25 19:21
Duplicate of #2358

**Closed** 2021-05-26 19:00 UTC
Labels: Bug, Duplicate
