### ISSUE TITLE
Pinned region detection crash

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1918] opened 2020-01-26 06:32 UTC
https://github.com/icsharpcode/ILSpy/blob/50e819345e2c04093431646b8bdb5580e81d0b0a/ICSharpCode.Decompiler/IL/ControlFlow/DetectPinnedRegions.cs#L549

`ldloc` was null.

`pinnedRegion.Descendants` contained:
```
[0] IL.LdsFlda
[1] IL.LdObj
[2] IL.Nop
[3] IL.Leave
[4] IL.Nop
[5] IL.Block
[6] IL.BlockContainer { containing only leave IL_0000; }
[7] IL.PinnedRegion
```

The following patch prevents the crash, but while the generated code _seems_ to be OK at first glance, I wouldn't bet my life on it:

```
diff --git a/ICSharpCode.Decompiler/IL/ControlFlow/DetectPinnedRegions.cs b/ICSharpCode.Decompiler/IL/ControlFlow/DetectPinnedRegions.cs
index d2f9206e..a3a57745 100644
--- a/ICSharpCode.Decompiler/IL/ControlFlow/DetectPinnedRegions.cs
+++ b/ICSharpCode.Decompiler/IL/ControlFlow/DetectPinnedRegions.cs
@@ -546,6 +546,8 @@ private void MoveArrayToPointerToPinnedRegionInit(PinnedRegion pinnedRegion)
                                                return; // variable access that is not LdLoc
                                }
                        }
+                       if (ldloc == null)
+                               return;
                        if (!(ldloc.Parent is GetPinnableReference arrayToPointer))
                                return;
                        if (!(arrayToPointer.Parent is Conv conv && conv.Kind == ConversionKind.StopGCTracking))
```

**Comment by siegfriedpammer** [comment] 2020-01-30 12:04
Do you have a small code sample that reproduces this exception? The fix looks good to me, because `ldloc` may be `null` if the loop is never entered at all.

**Comment by tamlin-mike** [comment] 2020-01-30 12:59
Afraid it's not so small.

The code is obfuscated. A pass through e.g. de4dot inlines the dummy-null types, so that part can safely be disregarded in this issue.

```
.method public hidebysig 
	instance void ProblemFunction (class [ExtAsm]ExtClass ''
	) cil managed 
{
	.maxstack 2
	.locals init (
		[0] valuetype [ExtAsm]ExtStruct[],
		[1] int32,
		[2] void*,
		[3] valuetype [ExtAsm]ExtStruct[] pinned,
		[4] native uint*,
		[5] native uint
	)

	IL_0000: ldarg.0
	ldfld class SomeList`1<valuetype [ExtAsm]ExtStruct> 'ThisAsm.ThisType'::m_list
	ldfld !0[] class SomeList`1<valuetype [ExtAsm]ExtStruct>::'array'
	stloc.0
	ldloc.0
	brtrue.s IL_0010
	ret

	IL_0010: ldarg.0
	ldfld class SomeList`1<valuetype [ExtAsm]ExtStruct> 'ThisAsm.ThisType'::m_list
	ldfld int32 class SomeList`1<valuetype [ExtAsm]ExtStruct>::Count
	stloc.1
	ldloc.0
	dup
	stloc.3
	brfalse.s IL_0026

	ldloc.3
	ldlen
	conv.i4
	brtrue.s IL_002b

	IL_0026: ldc.i4.0
	conv.u
	stloc.2
	br.s IL_0034

	IL_002b: ldloc.3
	ldc.i4.0
	ldelema [ExtAsm]ExtStruct
	conv.u
	stloc.2

	IL_0034: ldloc.2
	sizeof [mscorlib]System.UIntPtr
	sub
	stloc.s 4
	ldloc.s 4
	ldind.i
	stloc.s 5
	.try
	{
		ldloc.s 4
		ldloc.1
		conv.i8
		call native uint [mscorlib]System.UIntPtr::op_Explicit(uint64)
		stind.i
		ldarg.1
		ldloc.0
		callvirt instance void [ExtAsm]ExtClass::set_array(valuetype [ExtAsm]ExtStruct[])
		leave.s IL_005c
	} // end .try
	finally
	{
		ldloc.s 4
		ldloc.s 5
		stind.i
		endfinally
	} // end handler

	IL_005c: ldsfld valuetype [ExtAsm]ExtStruct[] 'NullObfuscator'::NullVal
	stloc.3
	ret
}
```

With the fix the following gets generated. Not valid code, but easy enough to fix up once you know the pattern.

```
using System;
using ExtAsmNamespace;

public unsafe void ProblemFunction(ExtClass P_0)
{
	ExtStruct[] array = ((SomeList<ExtStruct>*)(&this.m_list))->array;
	if (array != null)
	{
		int count = ((SomeList<ExtStruct>*)(&this.m_list))->Count;
		fixed (ExtStruct[] array2 = array)
		{
			void* ptr = (void*)(long)(IntPtr)(void*)/*OpCode not supported: GetPinnableReference*/;
			UIntPtr* ptr2 = (UIntPtr*)((byte*)ptr - sizeof(UIntPtr));
			UIntPtr uIntPtr = *ptr2;
			try
			{
				*ptr2 = (UIntPtr)(ulong)count;
				P_0.set_array(array);
			}
			finally
			{
				*ptr2 = uIntPtr;
			}
			fixed (ExtStruct[] array2 = NullObfuscator.NullVal)
			{
			}
		}
	}
}
```

What it basically does is bypassing the slowness of C#/CLR for array operations by using direct access. Save old count; Set count to claim it contains only N elements, to speed up the copying; Finally restore the saved count.

**Comment by dgrunwald** [comment] 2020-04-03 20:58
The obfuscated `NullVal` is problematic, pinned region detection depends on seeing the null assignment to find the end of the pinned region.
The pinned region detection didn't expect that another pinned region might start before the previous one ended.

Fixed by assuming the pinned region ends on any assignment to the pinned variable.

**Closed by dgrunwald** 2020-04-03 20:58 UTC
Labels: Bug, C#, Decompiler
