### ISSUE TITLE
descompiler monica 8.5

### ISSUE THREAD

**Issue by storz23** [icsharpcode/ILSpy#2836] opened 2022-11-15 15:49 UTC
Good morning, I need your help, I have the Monica 8.5 software and it can't be decompiled with ILSpy, does anyone know how I can decompile it?

**Comment by christophwille** [comment] 2022-11-15 16:10
Duplicate of discussion https://github.com/icsharpcode/ILSpy/discussions/2838

**Closed by christophwille** 2022-11-15 16:10 UTC
Labels: Enhancement
