### ISSUE TITLE
Doesn't accurately decompile casts

### ISSUE THREAD

**Issue by dustindavis** [icsharpcode/ILSpy#522] opened 2014-12-10 19:36 UTC
As shown in this SO question http://stackoverflow.com/questions/27409167/how-does-string-equalsa-b-not-produce-a-stackoverflowexception ILSpy misses the cast to object.

Decompile System.String and look at line 531

return a == b || (a != null && b != null && a.Length == b.Length && string.EqualsHelper(a, b));

a == b is the issue. The real code does this

public static bool Equals(String a, String b) {
            if ((Object)a==(Object)b) {
                return true;
            }

```
        if ((Object)a==null || (Object)b==null) {
            return false;
        }

        if (a.Length != b.Length)
            return false;

        return EqualsHelper(a, b);
    }
```

**Comment by dgrunwald** [comment] 2016-12-03 23:13
Duplicate of #217, which is fixed on the newdecompiler branch.

**Closed by dgrunwald** 2016-12-03 23:13 UTC
