### ISSUE TITLE
Unclickable Action<T> handler and Iterator.MoveNext()

### ISSUE THREAD

**Issue by Dentrax** [icsharpcode/ILSpy#1025] opened 2018-01-11 19:17 UTC
When you are browsing through the Analyzer window, when you click on Iterator.MoveNext() functions, it does not show-up to the code, nothing happens.

And also Action<T> parameters can be clicked in the old version, and now cannot be clickable.

Update : Also AnonStorey types can't be clickable from Analyzer windows.

Example of a project that has been decompiled ;

https://i.hizliresim.com/G91k03.png

Regards
![untitled](https://user-images.githubusercontent.com/16493751/34842746-7790507c-f71d-11e7-8621-636af6887a46.png)

**Comment by Dentrax** [comment] 2018-02-03 13:42
@siegfriedpammer Could you give some information about this status, please ? :)

**Comment by siegfriedpammer** [comment] 2018-02-04 10:03
This is likely because the analyzers scan the raw IL instructions and the decompiler hides some of that compiler-generated code. Therefore the analyzers show results that are not visible (because they are transformed back to their C# equivalents in the tree view and decompiler view), in your case: yield state machines, you could try disabling the yield decompiler if you are interested in seeing the invocations directly...

As for the action parameters: Yes, this is a known issue.

AnonStorey: Yes, because that's compiler-generated code that is hidden, same problem as described above...

Status/priority: low

**Comment by Dentrax** [comment] 2018-02-23 13:34
What is the class that controls these clickthrough events? Maybe I'm trying to do something myself with the educational purpose. Thanks... @siegfriedpammer

**Comment by siegfriedpammer** [comment] 2018-02-23 14:18
The references are added to the syntax tree in the transformation pipeline and then added to the output in `TextTokenWriter`. But that is not actually the problem. The main problem is, that the Analyzers do not run on the decompiled code, but on the raw IL. The reference to the MoveNext method is hidden/removed by the `YieldReturnDecompiler`. There is some functionality to map references to hidden elements back to their usage location, but it is not very well implemented (see `GetOriginalCodeLocation`), we would have to fix/extend that mechanism or replace it by a better solution.

**Comment by Dentrax** [comment] 2018-02-24 19:17
I analyzed the YieldReturnDecompiler.cs class. I don't understand anything except the class name. :) It's too long and complicated which is what it must be. In ILSpy 2, could be clicked because it was decompile in a different way, i think. 

P.S: The "EventManager" class given in the picture, full Gereric (T) and Action consists of the structure. There is no any IEnumerator structure.

**Comment by siegfriedpammer** [comment] 2018-02-26 19:29
I am unable to reproduce this... would you be able to post the assembly that causes the problem? Thank you!

**Comment by Dentrax** [comment] 2018-03-05 08:29
Sorry, I just saw now your comment. @siegfriedpammer 

Example.cs : https://pastebin.com/MgX2gVrj
Example.il  : https://pastebin.com/3uqZB2Aw

I can't click the "this.OnRunStarted" method from the "EventManager.Instance.RegisterHandler((Action<RunStartedEventArgs>)this.OnRunStarted);" here.

**Comment by Dentrax** [comment] 2018-03-11 10:23
Bump :)

**Comment by siegfriedpammer** [comment] 2018-03-11 10:52
By "assembly" I was asking for the binary, sorry for the confiusion. As this is a pure UI issue, it is way easier to debug having the actual binary. Thank you for your help!

**Comment by Dentrax** [comment] 2018-03-11 15:09
Thanks for your interest! 🥇 

I have just created a simple Unity-Mono project that have example Test case. There are 2 non-clickable functions. The first is the event call-back functions, the second is the IEnumerator references.
Also I've discovered a new error-bug. (?) Called with "Unable to find new state assignment for yield return".

Compiled assembly file: http://www.mediafire.com/file/ggru11bozxjo3i3/Issue1025.dll

Source file: http://www.mediafire.com/file/eua6eqlromnoblc/Issue1025_src.rar

Image:

![llld](https://user-images.githubusercontent.com/16493751/37254990-0b25f78a-2557-11e8-8ed5-c37c5a8f64fb.png)

Thanks... @siegfriedpammer

**Comment by dgrunwald** [comment] 2018-11-13 13:42
The "Error: unable to find new state assignment" is fixed now; but the other issues remain.

**Comment by siegfriedpammer** [comment] 2019-08-05 09:46
Triage:

* The yield return state machines from the example binary are now decompiled without any errors.
* The method groups are clickable.
* In order for the analyzers to find the compiler-generated members, they have to be visible in the tree view, please activate the "show all types and members setting"

Closing this.

**Closed by siegfriedpammer** 2019-08-05 09:46 UTC
