### ISSUE TITLE
Incorrect extension method delegate decompilation using C# 2.0

### ISSUE THREAD

**Issue by mikernet** [icsharpcode/ILSpy#1675] opened 2019-08-28 11:33 UTC
I believe this is where we post issues where SharpLab decompilation produces incorrect output, right?

This code sample results in incorrect C# output:

```c#
namespace ILExaminer
{
    using System;

    static class Program
    {
        internal static Func<T> AsFunc<T>(this T value)
            where T : class
        {
            return new Func<T>(value.Return); // this line becomes invalid
        }

        private static T Return<T>(this T value)
        {
            return value;
        }

        static void Main(string[] args)
        {
            Func<string> foo = "hi".AsFunc();
            string v = foo();
            Console.Write(v);
        }
    }
}
```

The invalid line translates to:

```c#
return new Func<T>(Return);
```

...which obviously can't work since `Return` doesn't have the right signature for `Func<T>`.

This bit of code is used to avoid closure allocation in the `AsFunc` method, and it seems that static extension method delegates use the delegate target as the first parameter:

```
    .method assembly hidebysig static 
        class [mscorlib]System.Func`1<!!T> AsFunc<class T> (
            !!T 'value'
        ) cil managed 
    {
        .custom instance void [mscorlib]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = (
            01 00 00 00
        )
        // Method begins at RVA 0x2050
        // Code size 23 (0x17)
        .maxstack 2
        .locals init (
            [0] class [mscorlib]System.Func`1<!!T>
        )

        IL_0000: nop
        IL_0001: ldarg.0
        IL_0002: box !!T
        IL_0007: ldftn !!0 ILExaminer.Program::Return<!!T>(!!0)
        IL_000d: newobj instance void class [mscorlib]System.Func`1<!!T>::.ctor(object, native int)
        IL_0012: stloc.0
        IL_0013: br.s IL_0015

        IL_0015: ldloc.0
        IL_0016: ret
    } // end of method Program::AsFunc
```

**Comment by siegfriedpammer** [comment] 2019-09-01 11:03
This is fixed on the current master.

Output of 5.0.0.5099-preview4:

```csharp
// ILExaminer.Program
using System;

internal static class Program
{
	internal static Func<T> AsFunc<T>(this T value) where T : class
	{
		return value.Return;
	}

	private static T Return<T>(this T value)
	{
		return value;
	}

	private static void Main(string[] args)
	{
		Func<string> foo = AsFunc("hi");
		string v = foo();
		Console.Write(v);
	}
}
```

@ashmind SharpLab should update once version 5.0 is released. Thank you!

**Comment by yyjdelete** [comment] 2019-09-02 02:18
@siegfriedpammer
This will happen only when choose `C#2.0`, or disable `Extension methods`.

**Comment by siegfriedpammer** [comment] 2019-09-02 04:25
@yyjdelete Ah I see, thank you!

How do you suggest we fix this issue?

As you cannot express a bound extension method reference unless extension method syntax is used, we will have to use extension method syntax anyway.

However, the problem is: once you select "C# 2.0" as a language version, we no longer detect that `Return` is an extension method, thus we won't know that the transformation is possible/necessary.

**Comment by siegfriedpammer** [comment] 2019-09-02 04:37
@mikernet which output would you expect, given that extension methods are not allowed due to decompilation settings chosen by sharplab? Thank you!

**Comment by mikernet** [comment] 2019-09-02 06:16
Oh...that's odd. Is there a reason SharpLab has extension methods disabled?I guess `Delegate.CreateDelegate()` makes the most sense, passing the object as the `firstParameter` parameter? I don't know what else you could do.On Sep. 2, 2019 12:38 a.m., Siegfried Pammer <notifications@github.com> wrote:@mikernet which output would you expect, given that extension methods are not allowed due to decompilation settings chosen by sharplab? Thank you!

**Comment by mikernet** [comment] 2019-09-02 06:17
Oh...that's odd. Is there a reason SharpLab has extension methods disabled?

I guess `Delegate.CreateDelegate()` makes the most sense, passing the object as the `firstParameter` parameter? I don't know what else you could do.

**Comment by ashmind** [comment] 2019-09-02 08:12
Yep, all syntax sugar is disabled by design. For example, people might use SharpLab to see how extension methods work.

From that perspective, I would prefer to generate something that is exactly right, even if it doesn't compile. E.g. something similar to "not supported" comments here:
https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCU+hxTAbgIYBO6AHugLzoA7AKYB3dAEsBAFwDaAXXzo4AGnQxVGAL4BuRkU3JNQA

While `Delegate.CreateDelegate()` would compile, it might be misleading for people trying to understand the internals of what C# compiler is doing there.

Maybe something like:
```
return new Func<T>(value, Return) /*Not supported: delegate constructor call with custom object*/;
```

**Comment by siegfriedpammer** [comment] 2019-09-27 14:11
We are going to implement this in the following way:

```csharp
return new Func<T>(value, ldftn(Return)); 
```

**Closed** 2019-09-27 16:37 UTC
Labels: Bug, C#, Decompiler
