### ISSUE TITLE
Keyboard Navigation in Tree always starts from beginning

### ISSUE THREAD

**Issue by SLaks** [icsharpcode/ILSpy#472] opened 2014-06-29 14:35 UTC
When I start typing with the symbol tree focus, it always selects the first node from the top that starts with those characters.

It should instead select the first node below the selected node that starts with those characters, like other tree views.

This would make navigation much easier.

**Comment by siegfriedpammer** [comment] 2017-09-07 09:40
Dupe of #67

**Closed by siegfriedpammer** 2017-09-07 09:40 UTC
