### ISSUE TITLE
I hope to get the Easy to understand code:

### ISSUE THREAD

**Issue by zgfflc** [icsharpcode/ILSpy#2400] opened 2021-05-09 11:23 UTC
I hope to get the Easy to understand code:
RunOnUiThread((Action)(() => progressBar_0.Progress = 40));

Now I get  hte Not very friendly to understand the code:
RunOnUiThread(delegate{progressBar_0.Progress = 40;});

Thank you!

**Comment by siegfriedpammer** [comment] 2021-05-17 19:25
Duplicate of #2243

**Closed by siegfriedpammer** 2021-05-17 19:25 UTC
Labels: Enhancement
