### ISSUE TITLE
System.InvalidCastException: Cast from Int64 to Object not supported.

### ISSUE THREAD

**Issue by little3388** [icsharpcode/ILSpy#1620] opened 2019-08-06 15:23 UTC
```
 ---> System.InvalidCastException: Cast from Int64 to Object not supported.
   at ICSharpCode.Decompiler.Util.CSharpPrimitiveCast.CSharpPrimitiveCastUnchecked(TypeCode targetType, Object input) in offset 3470
   at ICSharpCode.Decompiler.Util.CSharpPrimitiveCast.Cast(TypeCode targetType, Object input, Boolean checkForOverflow) in offset 28
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.<CreateTypedCaseLabel>d__13.MoveNext() in offset 565
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext() in offset 138
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source) in offset 114
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source) in offset 20
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.TranslateSwitch(BlockContainer switchContainer, SwitchInstruction inst) in offset 420
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlockContainer(BlockContainer container) in offset 159
   at ICSharpCode.Decompiler.IL.BlockContainer.AcceptVisitor[T](ILVisitor`1 visitor) in offset 1
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 16
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlock(Block block) in offset 55
   at ICSharpCode.Decompiler.IL.Block.AcceptVisitor[T](ILVisitor`1 visitor) in offset 1
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 16
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertAsBlock(ILInstruction inst) in offset 1
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertLoop(BlockContainer container) in offset 963
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlockContainer(BlockContainer container) in offset 52
   at ICSharpCode.Decompiler.IL.BlockContainer.AcceptVisitor[T](ILVisitor`1 visitor) in offset 1
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 16
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockStatement blockStatement, BlockContainer container, IEnumerable`1 blocks, Boolean isLoop) in offset 156
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockContainer container, Boolean isLoop) in offset 7
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlockContainer(BlockContainer container) in offset 173
   at ICSharpCode.Decompiler.IL.BlockContainer.AcceptVisitor[T](ILVisitor`1 visitor) in offset 1
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 16
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertAsBlock(ILInstruction inst) in offset 1
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitTryCatch(TryCatch inst) in offset 15
   at ICSharpCode.Decompiler.IL.TryCatch.AcceptVisitor[T](ILVisitor`1 visitor) in offset 1
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 16
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockStatement blockStatement, BlockContainer container, IEnumerable`1 blocks, Boolean isLoop) in offset 156
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockContainer container, Boolean isLoop) in offset 7
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlockContainer(BlockContainer container) in offset 173
   at ICSharpCode.Decompiler.IL.BlockContainer.AcceptVisitor[T](ILVisitor`1 visitor) in offset 1
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 16
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertAsBlock(ILInstruction inst) in offset 1
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 724
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 1084
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 249
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 782
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in offset 219
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in offset 201
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass34_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 69
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1() in offset 589
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) in offset 6
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object) in offset 134
```

**Comment by siegfriedpammer** [comment] 2019-08-06 15:31
Could you please provide the assembly that causes this exception? Thank you very much!

**Comment by siegfriedpammer** [comment] 2019-08-24 06:51
@little3388 Any update on this? Thank you!

**Comment by little3388** [comment] 2019-09-16 15:37
> Could you please provide the assembly that causes this exception? Thank you very much!

Has been resolved, modify the following method

private static object CSharpPrimitiveCastUnchecked(TypeCode targetType, object input)
{
	TypeCode typeCode = Type.GetTypeCode(input.GetType());
	if (typeCode != targetType)
	{
		switch (targetType)
		{
		case TypeCode.Object:
			switch (typeCode)
			{
			case TypeCode.SByte:
				return (char)(sbyte)input;
			case TypeCode.Byte:
				return (char)(byte)input;
			case TypeCode.Int16:
				return (char)(short)input;
			case TypeCode.UInt16:
				return (char)(ushort)input;
			case TypeCode.Int32:
				return (char)(int)input;
			case TypeCode.UInt32:
				return (char)(uint)input;
			case TypeCode.Int64:
				return (char)(long)input;
			case TypeCode.UInt64:
				return (char)(ulong)input;
			case TypeCode.Single:
				return (char)(float)input;
			case TypeCode.Double:
				return (char)(double)input;
			case TypeCode.Decimal:
				return (char)(char)(decimal)input;
			}
			break;
		case TypeCode.Char:
			switch (typeCode)
			{
			case TypeCode.SByte:
				return (char)(sbyte)input;
			case TypeCode.Byte:
				return (char)(byte)input;
			case TypeCode.Int16:
				return (char)(short)input;
			case TypeCode.UInt16:
				return (char)(ushort)input;
			case TypeCode.Int32:
				return (char)(int)input;
			case TypeCode.UInt32:
				return (char)(uint)input;
			case TypeCode.Int64:
				return (char)(long)input;
			case TypeCode.UInt64:
				return (char)(ulong)input;
			case TypeCode.Single:
				return (char)(float)input;
			case TypeCode.Double:
				return (char)(double)input;
			case TypeCode.Decimal:
				return (char)(char)(decimal)input;
			}
			break;
		case TypeCode.SByte:
			switch (typeCode)
			{
			case TypeCode.Char:
				return (sbyte)(char)input;
			case TypeCode.Byte:
				return (sbyte)(byte)input;
			case TypeCode.Int16:
				return (sbyte)(short)input;
			case TypeCode.UInt16:
				return (sbyte)(ushort)input;
			case TypeCode.Int32:
				return (sbyte)(int)input;
			case TypeCode.UInt32:
				return (sbyte)(uint)input;
			case TypeCode.Int64:
				return (sbyte)(long)input;
			case TypeCode.UInt64:
				return (sbyte)(ulong)input;
			case TypeCode.Single:
				return (sbyte)(float)input;
			case TypeCode.Double:
				return (sbyte)(double)input;
			case TypeCode.Decimal:
				return (sbyte)(sbyte)(decimal)input;
			}
			break;
		case TypeCode.Byte:
			switch (typeCode)
			{
			case TypeCode.Char:
				return (byte)(char)input;
			case TypeCode.SByte:
				return (byte)(sbyte)input;
			case TypeCode.Int16:
				return (byte)(short)input;
			case TypeCode.UInt16:
				return (byte)(ushort)input;
			case TypeCode.Int32:
				return (byte)(int)input;
			case TypeCode.UInt32:
				return (byte)(uint)input;
			case TypeCode.Int64:
				return (byte)(long)input;
			case TypeCode.UInt64:
				return (byte)(ulong)input;
			case TypeCode.Single:
				return (byte)(float)input;
			case TypeCode.Double:
				return (byte)(double)input;
			case TypeCode.Decimal:
				return (byte)(byte)(decimal)input;
			}
			break;
		case TypeCode.Int16:
			switch (typeCode)
			{
			case TypeCode.Char:
				return (short)(char)input;
			case TypeCode.SByte:
				return (short)(sbyte)input;
			case TypeCode.Byte:
				return (short)(byte)input;
			case TypeCode.UInt16:
				return (short)(ushort)input;
			case TypeCode.Int32:
				return (short)(int)input;
			case TypeCode.UInt32:
				return (short)(uint)input;
			case TypeCode.Int64:
				return (short)(long)input;
			case TypeCode.UInt64:
				return (short)(ulong)input;
			case TypeCode.Single:
				return (short)(float)input;
			case TypeCode.Double:
				return (short)(double)input;
			case TypeCode.Decimal:
				return (short)(short)(decimal)input;
			}
			break;
		case TypeCode.UInt16:
			switch (typeCode)
			{
			case TypeCode.Char:
				return (ushort)(char)input;
			case TypeCode.SByte:
				return (ushort)(sbyte)input;
			case TypeCode.Byte:
				return (ushort)(byte)input;
			case TypeCode.Int16:
				return (ushort)(short)input;
			case TypeCode.Int32:
				return (ushort)(int)input;
			case TypeCode.UInt32:
				return (ushort)(uint)input;
			case TypeCode.Int64:
				return (ushort)(long)input;
			case TypeCode.UInt64:
				return (ushort)(ulong)input;
			case TypeCode.Single:
				return (ushort)(float)input;
			case TypeCode.Double:
				return (ushort)(double)input;
			case TypeCode.Decimal:
				return (ushort)(ushort)(decimal)input;
			}
			break;
		case TypeCode.Int32:
			switch (typeCode)
			{
			case TypeCode.Char:
				return (int)(char)input;
			case TypeCode.SByte:
				return (int)(sbyte)input;
			case TypeCode.Byte:
				return (int)(byte)input;
			case TypeCode.Int16:
				return (int)(short)input;
			case TypeCode.UInt16:
				return (int)(ushort)input;
			case TypeCode.UInt32:
				return (int)(uint)input;
			case TypeCode.Int64:
				return (int)(long)input;
			case TypeCode.UInt64:
				return (int)(ulong)input;
			case TypeCode.Single:
				return (int)(float)input;
			case TypeCode.Double:
				return (int)(double)input;
			case TypeCode.Decimal:
				return (int)(int)(decimal)input;
			}
			break;
		case TypeCode.UInt32:
			switch (typeCode)
			{
			case TypeCode.Char:
				return (uint)(char)input;
			case TypeCode.SByte:
				return (uint)(sbyte)input;
			case TypeCode.Byte:
				return (uint)(byte)input;
			case TypeCode.Int16:
				return (uint)(short)input;
			case TypeCode.UInt16:
				return (uint)(ushort)input;
			case TypeCode.Int32:
				return (uint)(int)input;
			case TypeCode.Int64:
				return (uint)(long)input;
			case TypeCode.UInt64:
				return (uint)(ulong)input;
			case TypeCode.Single:
				return (uint)(float)input;
			case TypeCode.Double:
				return (uint)(double)input;
			case TypeCode.Decimal:
				return (uint)(uint)(decimal)input;
			}
			break;
		case TypeCode.Int64:
			switch (typeCode)
			{
			case TypeCode.Char:
				return (long)(char)input;
			case TypeCode.SByte:
				return (long)(sbyte)input;
			case TypeCode.Byte:
				return (long)(byte)input;
			case TypeCode.Int16:
				return (long)(short)input;
			case TypeCode.UInt16:
				return (long)(ushort)input;
			case TypeCode.Int32:
				return (long)(int)input;
			case TypeCode.UInt32:
				return (long)(uint)input;
			case TypeCode.UInt64:
				return (long)(ulong)input;
			case TypeCode.Single:
				return (long)(float)input;
			case TypeCode.Double:
				return (long)(double)input;
			case TypeCode.Decimal:
				return (long)(long)(decimal)input;
			}
			break;
		case TypeCode.UInt64:
			switch (typeCode)
			{
			case TypeCode.Char:
				return (ulong)(char)input;
			case TypeCode.SByte:
				return (ulong)(sbyte)input;
			case TypeCode.Byte:
				return (ulong)(byte)input;
			case TypeCode.Int16:
				return (ulong)(short)input;
			case TypeCode.UInt16:
				return (ulong)(ushort)input;
			case TypeCode.Int32:
				return (ulong)(int)input;
			case TypeCode.UInt32:
				return (ulong)(uint)input;
			case TypeCode.Int64:
				return (ulong)(long)input;
			case TypeCode.Single:
				return (ulong)(float)input;
			case TypeCode.Double:
				return (ulong)(double)input;
			case TypeCode.Decimal:
				return (ulong)(ulong)(decimal)input;
			}
			break;
		case TypeCode.Single:
			switch (typeCode)
			{
			case TypeCode.Char:
				return (float)(float)(int)(char)input;
			case TypeCode.SByte:
				return (float)(float)(sbyte)input;
			case TypeCode.Byte:
				return (float)(float)(int)(byte)input;
			case TypeCode.Int16:
				return (float)(float)(short)input;
			case TypeCode.UInt16:
				return (float)(float)(int)(ushort)input;
			case TypeCode.Int32:
				return (float)(float)(int)input;
			case TypeCode.UInt32:
				return (uint)input;
			case TypeCode.Int64:
				return (float)(float)(long)input;
			case TypeCode.UInt64:
				return (ulong)input;
			case TypeCode.Double:
				return (float)(double)input;
			case TypeCode.Decimal:
				return (float)(float)(decimal)input;
			}
			break;
		case TypeCode.Double:
			switch (typeCode)
			{
			case TypeCode.Char:
				return (double)(double)(int)(char)input;
			case TypeCode.SByte:
				return (double)(double)(sbyte)input;
			case TypeCode.Byte:
				return (double)(double)(int)(byte)input;
			case TypeCode.Int16:
				return (double)(double)(short)input;
			case TypeCode.UInt16:
				return (double)(double)(int)(ushort)input;
			case TypeCode.Int32:
				return (double)(double)(int)input;
			case TypeCode.UInt32:
				return (uint)input;
			case TypeCode.Int64:
				return (double)(double)(long)input;
			case TypeCode.UInt64:
				return (ulong)input;
			case TypeCode.Single:
				return (double)(float)input;
			case TypeCode.Decimal:
				return (double)(double)(decimal)input;
			}
			break;
		case TypeCode.Decimal:
			switch (typeCode)
			{
			case TypeCode.Char:
				return (char)input;
			case TypeCode.SByte:
				return (sbyte)input;
			case TypeCode.Byte:
				return (byte)input;
			case TypeCode.Int16:
				return (short)input;
			case TypeCode.UInt16:
				return (ushort)input;
			case TypeCode.Int32:
				return (int)input;
			case TypeCode.UInt32:
				return (uint)input;
			case TypeCode.Int64:
				return (long)input;
			case TypeCode.UInt64:
				return (ulong)input;
			case TypeCode.Single:
				return (decimal)(float)(float)input;
			case TypeCode.Double:
				return (decimal)(double)(double)input;
			}
			break;
		}
		throw new InvalidCastException("Cast from " + typeCode + " to " + targetType + " not supported.");
	}
	return input;
}

**Comment by siegfriedpammer** [comment] 2019-09-17 03:48
Adding conversions from Object to a primitive type does not make sense at all. The `CSharpPrimitiveCast` class is not meant to be used in that way. Conversions from object to a primitive type can only be done through unboxing.

In order for us to implement the correct fix, please either provide the assembly or the IL code causing the problem. Thank you very much!

**Comment by siegfriedpammer** [comment] 2019-09-27 14:07
Could not reproduce. Closing.

**Closed by siegfriedpammer** 2019-09-27 14:07 UTC
Labels: Bug, C#, Decompiler, Feedback Needed
