### ISSUE TITLE
System.BadImageFormatException: Invalid coded index

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1231] opened 2018-07-22 17:52 UTC
ILSpy version 4.0.0.4225-alpha1

```
System.BadImageFormatException: Invalid coded index.
   at System.Reflection.Throw.InvalidCodedIndex()
   at System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(TypeDefinitionHandle handle)
   at ICSharpCode.Decompiler.SRMExtensions.IsEnum(TypeDefinition typeDefinition, MetadataReader reader, PrimitiveTypeCode& underlyingType)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataTypeDefinition..ctor(MetadataModule module, TypeDefinitionHandle handle)
   at ICSharpCode.Decompiler.TypeSystem.MetadataModule.GetDefinition(TypeDefinitionHandle handle)
   at ICSharpCode.Decompiler.TypeSystem.MetadataModule.<get_TypeDefinitions>d__40.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass34_0.<DecompileAsync>b__0()

```
target: https://www.sendspace.com/file/gex0bz

**Comment by siegfriedpammer** [comment] 2018-07-22 21:36
The `BaseType` token of the `<Module>` type is 0xFFFF, which is not a valid value. Other than that the assembly seems to be fine.

@dgrunwald how are we going to protect against such exceptions?
@tmat @sharwell Any chance to improve SRM in this area? Also, would it be possible to allow getting the raw value of the token?

**Comment by sharwell** [comment] 2018-07-23 00:15
Do we know why the assembly contains invalid metadata? Seems like a bug that should be fixed.

**Comment by siegfriedpammer** [comment] 2018-07-23 05:51
It's obfuscated, ildasm won't process it as well.
But VS is able to show intellisense at least for the "human readable" namespaces.

**Comment by sharwell** [comment] 2018-07-23 08:41
> It's obfuscated

At last check we decided to "won't fix" items related to obfuscated assemblies.

**Comment by siegfriedpammer** [comment] 2018-07-23 09:10
@sharwell thanks for the clarification.
@greenozon I'm sorry, we won't be able to support obfuscated assemblies anymore. Please go use any other decompiler: dotPeek, dnSpy, whichever you prefer.

**Comment by dgrunwald** [comment] 2018-07-23 09:40
What's happening here is that SRM throws an exceptions on invalid metadata, where Cecil pretended that the invalid metadata didn't exist at all.
So strictly speaking, SRM provides us more information here than Cecil did, it's just unfortunately that we constantly have to catch exceptions...

**Closed** 2018-07-23 09:56 UTC

**Comment by sharwell** [comment] 2018-07-23 19:20
> At last check we decided to "won't fix" items related to obfuscated assemblies.

By the way, the issue here is there is virtually an unlimited number of edge cases which obfuscation tools use to try and break decompilation tools. In all cases, two things are apparent:

1. The file is not following the rules, and therefore is not expected (certainly not guaranteed) to work in any specific capacity, including but not limited to compilation (as a dependency) or runtime
2. The intent of the author of the file is clearly to break tools, so if the tool is broken, it's not a bug and there is nothing to fix
