### ISSUE TITLE
Assertion failed in DeconstructInstruction.cs:314

### ISSUE THREAD

**Issue by marwie** [icsharpcode/ILSpy#2429] opened 2021-06-07 09:15 UTC
### Steps to reproduce
1) Download Unity 2021.2.0a10 or a8
2) Run command ``ilspycmd.exe path/to/Unity.IL2CPP.dll -o path/to/output -p --languageversion Latest``

### Error message shown
```csharp
Process terminated. Assertion failed.
   at ICSharpCode.Decompiler.IL.DeconstructInstruction.<CheckInvariant>g__ValidatePattern|30_0(MatchInstruction inst, <>c__DisplayClass30_0& ) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Instructions\DeconstructInstruction.cs:line 314
   at ICSharpCode.Decompiler.IL.DeconstructInstruction.CheckInvariant(ILPhase phase) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Instructions\DeconstructInstruction.cs:line 282
   at ICSharpCode.Decompiler.IL.Transforms.StatementTransform.Run(Block block, BlockTransformContext context) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\StatementTransform.cs:line 137
   at ICSharpCode.Decompiler.IL.Block.RunTransforms(IEnumerable`1 transforms, BlockTransformContext context) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Instructions\Block.cs:line 318
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\BlockTransform.cs:line 118
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.Run(ILFunction function, ILTransformContext context) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\BlockTransform.cs:line 90
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 1495
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 1431
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 1269
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 559
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 879
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\ProjectDecompiler\WholeProjectDecompiler.cs:line 240
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.Tasks.TaskReplicator.Replica.<>c.<Execute>b__7_0(Object s)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

### Details
* Product in use: ILSpy
* Version in use:  latest master 353ce882664b7ea8a9536da7e5fa3acea1604650

**Comment by siegfriedpammer** [comment] 2021-11-07 18:29
Duplicate of #2378

**Closed by siegfriedpammer** 2021-11-07 18:29 UTC
Labels: Bug
