### ISSUE TITLE
Decompiler exception when decompiling SharpSvn (1.8009.3299.43)

### ISSUE THREAD

**Issue by shahar-ma** [icsharpcode/ILSpy#594] opened 2015-04-15 03:05 UTC
ICSharpCode.Decompiler.DecompilerException: Error decompiling svn_error_t\* modopt(System.Runtime.CompilerServices.CallConvCdecl) <Module>::?A0x12823cd1.sharpsvn_check_bdb()
 ---> System.InvalidCastException: Unable to cast object of type 'Mono.Cecil.TypeReference' to type 'Mono.Cecil.PointerType'.
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.HandlePointerArithmetic(ILNode method)
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, ILAstOptimizationStep abortBeforeStep)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethod(MethodDefinition methodDef)
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddTypeMembers(TypeDeclaration astType, TypeDefinition typeDef)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateType(TypeDefinition typeDef)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(TypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass16.<DecompileAsync>b__15()

**Comment by 0xd4d** [comment] 2015-04-15 04:24
Seems like a dupe of #592

**Closed** 2017-10-03 13:49 UTC
