### ISSUE TITLE
NullReferenceException when generating a pdb

### ISSUE THREAD

**Issue by NitzanEgozy** [icsharpcode/ILSpy#1945] opened 2020-03-04 11:12 UTC
When decompiling some specific DLLs we encounter a NullReferenceException:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.CSharp.SequencePointBuilder.AddToSequencePoint(ILInstruction inst)
   at ICSharpCode.Decompiler.CSharp.SequencePointBuilder.AddToSequencePoint(AstNode node)
   at ICSharpCode.Decompiler.CSharp.Syntax.DepthFirstAstVisitor.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.SequencePointBuilder.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.Syntax.DepthFirstAstVisitor.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.SequencePointBuilder.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.Syntax.DepthFirstAstVisitor.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.SequencePointBuilder.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.SequencePointBuilder.VisitAsSequencePoint(AstNode node)
   at ICSharpCode.Decompiler.CSharp.SequencePointBuilder.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.Decompiler.CSharp.Syntax.DepthFirstAstVisitor.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.SequencePointBuilder.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.Syntax.DepthFirstAstVisitor.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.SequencePointBuilder.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.Syntax.DepthFirstAstVisitor.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.SequencePointBuilder.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.Syntax.DepthFirstAstVisitor.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.SequencePointBuilder.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.DebugInfo.PortablePdbWriter.WritePdb(PEFile file, CSharpDecompiler decompiler, DecompilerSettings settings, Stream targetStream, Boolean noLogo)
   at ICSharpCode.ILSpy.GeneratePdbContextMenuEntry.<>c__DisplayClass3_0.<GeneratePdbForAssembly>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

To replicate:
Download [PaintDotNet.Core.dll.zip](https://github.com/icsharpcode/ILSpy/files/4286934/PaintDotNet.Core.dll.zip)
Open with ILSpy
Right-click and choose "Generate portable PDB". See the exception.
Tested on latest ILSpy 5.0.2 and 6.0 Preview 2

**Comment by jacdavis** [comment] 2020-03-04 19:40
I was coming to file this exact issue. In my testing, I ran ilspycmd with -d against approximately 1000 managed modules that are components of VS. It crashed on about 23 of them with this same or similar error. 

One example was decompiling System.Console.dll. Here was our analysis of the crash:
What's happening is that the decompilation creates an AST from the read in IL stream for each method and uses the AST to generate sequence points, debug information, etc. In the System.Console assembly, it is failing to create sequence points for the System.Text.OSEncoder.ConvertWithLeftOverChar method. This method contains a C# stackalloc call for 2 chars, which is actually a ldc.i4.4, conv, and localloc in the IL. When creating the AST for this code, it translates the ldc.i4.4 and conv instructions into a single primitive expression node that has a ldc.i4.2 annotation instruction (it changes the constant because the original ldc.i4.4 is saying to alloc 4 bytes from the local memory pool, but each index into this blob of memory is a char, which is 2 bytes; thus 4 bytes / 2 chars = 2 indexes, hence ldc.i4.2). However, this ldc.i4.2 instruction does not have a parent since it is a virtual instruction. The sequence point builder is a depth first visitor on ASTs and adds the instructions found as annotations on each AST node to the currently generated sequence point. This algorithm uses the parent of the instruction to find the ancestor ILFunction, but since this ldc.i4.2 instruction doesn't have a parent, it throws a NullReferenceException.

This can be fixed by using the AstNode to find the ancestor MethodDeclaration and then get the ILFunction from its Annotations collection.

**Comment by siegfriedpammer** [comment] 2020-03-04 20:24
This seems to be a duplicate of #1851.

**Closed** 2020-03-31 19:08 UTC
Labels: Bug, PDBGen
