### ISSUE TITLE
ILSpy cannot decompile files that have stack layout that doesn't comply with the .Net specifications, i.e. Obfuscated files

### ISSUE THREAD

**Issue by MostafaNanticock** [icsharpcode/ILSpy#1565] opened 2019-07-09 11:58 UTC
ILSpy is a great project & i've been using it since it's early releases, in fact i was able to learn c# by only compiling VB Code & see the results of the decompilation process in c#, but that's beside the point. what matters is that it's very effective that it can decompile even obfuscated files & sometimes you would be able to build the decompilation result directly without any modifications. but when it comes to obfuscated files with unbalanced stacks it starts to loose it's efficiency & begins to add comments in the code that tells you that it wasn't able to Decompile this function because of unbalanced stack Lengths. but i think that even this can be overcome & it isn't that hard to be done. IDA can decompile almost any native executable & generate C code out of it, and of course you know that Decompiling IL is much easier than decompiling assembly.

**Comment by christophwille** [comment] 2019-07-09 12:10
If it is easy, please feel free to provide a pull request.

**Comment by siegfriedpammer** [comment] 2019-07-13 14:16
Can you please provide a concrete example (binary) that shows the problem you are experiencing? Thank you very much!

**Comment by dgrunwald** [comment] 2019-07-13 17:53
Our `ILReader` currently reads all bytecode in the method.
The .NET runtime only reads reachable blocks; where the exact definition of "reachable" varies between different .NET versions. Any bytecode fragments that are never read have no effect on the evaluation stack; so .NET can end up inferring different types on the evaluation stack depending on the .NET version and optimization level.

See also #901 and #1242.

**Comment by siegfriedpammer** [comment] 2019-08-10 09:19
Closing because of no feedback and essentially duplicate of #901 and #1242.

**Closed by siegfriedpammer** 2019-08-10 09:19 UTC
Labels: Feedback Needed
