### ISSUE TITLE
The lastest version can not decompile anything.

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#997] opened 2017-11-30 05:45 UTC
System.BadImageFormatException: 可执行文件(.exe)或库(.dll)的格式无效。
   在 Mono.Cecil.PE.ImageReader.ReadImage()
   在 Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   在 Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   在 ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ICSharpCode.ILSpy.LoadedAssembly.<GetAssemblyDefinitionAsync>d__10.MoveNext()

**Comment by siegfriedpammer** [comment] 2017-11-30 08:37
I cannot reproduced this on my machine. `3.0.0.3375-beta3` is happily decompiling on my machine.

![grafik](https://user-images.githubusercontent.com/344204/33421336-ff227480-d5b1-11e7-8e6c-478cb648bbe9.png)

Could you please be more specific? Thanks!

**Comment by CreateAndInject** [comment] 2017-11-30 09:03
It works after deleting some assemblies.
But I don't care which files I deleted.
It seems ILSpy will save the assemblies list when exit.
Now, I don't exit the process. Tell me where I can find the assembly list on my hard disk.

**Comment by siegfriedpammer** [comment] 2017-11-30 09:13
`%appdata%\ICSharpCode\ILSpy.xml`

I still don't fully understand your problem... could you please post a screenshot? Is this a hard crash, or is it displayed in the decompiler code view?

![grafik](https://user-images.githubusercontent.com/344204/33422776-0c55706c-d5b7-11e7-865e-17f7f2b21596.png)

**Comment by CreateAndInject** [comment] 2017-11-30 09:15
ILSpy will save assemblies list when I delete assembly immediately, so I can't find which I deleted.

**Comment by CreateAndInject** [comment] 2017-11-30 09:16
It seems when one assembly is invalid, all the assemblies will be invalid.

**Comment by CreateAndInject** [comment] 2017-11-30 09:19
I can reproduce (but the error msg is different, so I am not sure)
Open ILSpy, drag one file to. then close ILSpy.
Delete the file in the hard disk, and open ILSpy.

**Comment by CreateAndInject** [comment] 2017-11-30 09:25
I can reproduce with the same message:
Drag an invalid file(such as .txt file), then all the assemblies are invalid.

**Comment by siegfriedpammer** [comment] 2017-11-30 09:36
Should be fixed now! Thanks for the report!

**Closed** 2017-11-30 09:35 UTC
