### ISSUE TITLE
System.InvalidOperationException: At least one project is expected.

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1662] opened 2019-08-24 09:26 UTC
ILSpy version 5.0.0.5093-preview4

strange error is occuring when saving all files (together, as a solution) from attachment 
issue not present when saving 1 at a time, separately.

```
System.InvalidOperationException: At least one project is expected.
   at ICSharpCode.Decompiler.Solution.SolutionCreator.WriteSolutionFile(String targetFile, IEnumerable`1 projects)
   at ICSharpCode.ILSpy.SolutionWriter.<>c__DisplayClass6_0.<CreateSolution>b__1()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at ICSharpCode.ILSpy.SolutionWriter.<CreateSolution>d__6.MoveNext()
```

I've seen other errors (not occuring when doing 1 assembly at a time, will report separately once find it again

https://www.sendspace.com/file/8t0c75

**Comment by siegfriedpammer** [comment] 2019-08-24 17:19
Sorry, I could not reproduce the exception.

Here's what I did:
1) Open both assemblies; no other assemblies are in the list
2) Select both assembly tree nodes
3) Click "Save Code"
4) The assemblies are decompiled to projects and the solution is created successfully.

I used rev. 5096, however, we didn't change anything in that area of the code recently.

**Comment by siegfriedpammer** [comment] 2020-04-02 17:53
Closing, due to missing feedback for over 6 months.

**Closed by siegfriedpammer** 2020-04-02 17:53 UTC
Labels: Feedback Needed
