### ISSUE TITLE
FR: Symbols removal & renaming in the ILSpy GUI

### ISSUE THREAD

**Issue by RedStoneMatt** [icsharpcode/ILSpy#3260] opened 2024-08-15 10:03 UTC
**Is your feature request related to a problem? Please describe.**

Some obfuscated programs change all of their symbols (class names, function names, etc) into junk to make it harder to understand the problem (sometimes they make all names be whitespaces, or numbers written as strings).

**Describe the solution you'd like**

It would be nice to be able to disable the symbols names provided by these programs and have them replace by default ones (kinda like local variables) and then once a symbol has been understood, being able to right click it to rename it to something understandable.

**Comment by siegfriedpammer** [comment] 2024-08-15 14:03
Duplicate of #209

**Closed** 2024-12-14 11:39 UTC
Labels: Enhancement
