### ISSUE TITLE
BSOD when clicking on "Data Directories" in metadata explorer.

### ISSUE THREAD

**Issue by Leowbattle** [icsharpcode/ILSpy#2074] opened 2020-07-19 13:41 UTC
### Steps to reproduce
1. Open an assembly in ILSpy
2. Expand the metadata explorer
3. Click on "data directories"

### Error message shown
This is the error message shown for "DOS header". I show this one instead of the real one because it is the same kind of error window and I don't want to get a picture of the real message because it will crash the computer again. The program goes into some kind of loop opening these windows until a BSOD occurs.
![error](https://user-images.githubusercontent.com/26633478/87876098-a6139000-c9cd-11ea-9871-55fb35372b03.png)

### Details
* Version: 6.0.0.5836
* The DOS header and Optional header buttons also show an error message window, but only open 1 and don't cause a BSOD. I'm not sure if clicking on any of the metadata tables cause BSODs because I have not tried clicking them yet and don't want to because I don't want to crash my computer again.

**Comment by Leowbattle** [comment] 2020-07-19 13:44
Out of curiosity I did click on a metadata table and it went into the same loop of opening error windows, but I managed to close ILSpy with Task Manager before it crashed the computer.

**Comment by siegfriedpammer** [comment] 2020-07-20 12:38
I cannot reproduce this. Does this occur with every assembly? The exception shown in the screenshot does not make any sense to me. I checked whether the type is missing from the assembly - but it's not:

![image](https://user-images.githubusercontent.com/344204/87937830-bf800f00-ca95-11ea-9bd9-61bc00cd3737.png)

Also it is very strange that a simple exception thrown during XAML parsing/loading causes a BSOD. Without a memory dump it is impossible to find the root cause, but this smells like a memory or (graphics?) driver error. Not sure how I would be able to help you.

**Comment by dgrunwald** [comment] 2020-07-22 19:34
With a crash in WPF `Measure` it's possible that the crash occurs repeatedly, and thus opened a huge amount of dialog boxes.
This could cause blue screens back in Windows 1998; but that shouldn't happen with any Windows version more modern than that...

Still clueless as to what was causing the original exception. Do you have a DataGridExtensions.dll next to ILSpy.exe?

**Comment by siegfriedpammer** [comment] 2020-07-23 09:47
> The reason I didn't get a screenshot of the "Data directories" error message is because I do not want to BSOD my computer again.

Do you have access to another computer and might be able to try ILSpy there? A VM might work as well. I understand that you don't want to crash your computer deliberately.

**Comment by christophwille** [comment] 2020-08-07 07:42
Closing after > 2 weeks no feedback.

**Closed by christophwille** 2020-08-07 07:42 UTC
Labels: Bug, Feedback Needed
