### ISSUE TITLE
Filenames and directories truncated to 30 characters

### ISSUE THREAD

**Issue by avengerx** [icsharpcode/ILSpy#2706] opened 2022-06-11 21:38 UTC
### Input code
Just make a simple project with an embedded resource file name with more than 30 characters, example:
`mylongfilenameherebuthereandherealso.txt`

### Erroneous output
The file will be output as:
`mylongfilenameherebuthereandhe.txt` (if I counted right, 30 characters)

### Details
* Product in use: ILSpyCmd (dotnet tool),
* Version in use: 8.0.0.7047 (prerelease, pulled from latest `master` build workflow)

This was also reproduced in 7.2.0.0.rc version of the `Our Linux/Mac/Windows ILSpy UI based on [Avalonia](http://www.avaloniaui.net/) - check out https://github.com/icsharpcode/AvaloniaILSpy` (found in [README.md](https://github.com/icsharpcode/ILSpy/blob/v8.0-preview1/README.md?plain=1#L18)

Also reproduced in the windows GUI I downloaded, version: ILSpy version 7.2.1.6856. (sorry, I'm not sure, was it from MS Store?.. not sure... it works better than AvalonUI one).

Besides embedded resource filenames, for instance, if we don't `--nested-directories`, and the namespace goes beyond 30 characters, the same happens to the output directory name: truncated at 30 characters. The actual namespace in the output file is complete.

While all links in the end project works well, in case the project has a reference or path to that embedded resource (if using string/reflection for instance), that would break the decompiled code (thus I believe this is a bug).

**Comment by avengerx** [comment] 2022-06-11 23:24
I see... I ... think... I see.. :P

But if `HKLM/System/CurrentControlSet/Control/FileSystem/LongPathsEnabled` is 0 on windows (95+?) this just means file name length is limited to 260 characters, not just 30. When this setting is 1, it means Windows FS will support filenames with _over_ 260 chars. That's what I read here: [LongPathsEnabled in Windows docs Q&A site](https://docs.microsoft.com/en-us/answers/questions/293227/longpathsenabled.html)

For the long-term record, a summary of the question:
> _"Is the registry setting [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem] LongPathsEnabled supported in Windows Server 2019? Is it supposed to work?"_

And the answer:
> _"By setting the registry key LongPathsEnabled to 1, most of the common Win32 file and directory functions will be able to use file paths exceeding 260 characters._
> 
> _However, with the option enabled, Explorer still fails to use long file paths. Explorer is not long filepath aware. This is a by design behavior, as there are a lot of legacy APIs and DLLs which win32 applications depend on."_

So I guess we should be good to use 255 always, when [`PlatformID.Win32NT`](https://github.com/icsharpcode/ILSpy/blob/e2d79774cd3eb98b2b14f2a1fbeda1d9d0089d60/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs#L551).

Here's the actual documentation page on the registry key: [Maximum Path Length Limitation](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd)

And according to that doc page, when the registry key is enabled, the path length limitation is raised to 32,767.

**Comment by siegfriedpammer** [comment] 2022-06-12 10:04
> But if `HKLM/System/CurrentControlSet/Control/FileSystem/LongPathsEnabled` is 0 on windows (95+?) this just means file name length is limited to 260 characters, not just 30. When this setting is 1, it means Windows FS will support filenames with _over_ 260 chars.

First of all this feature was added recently to Windows 10, not Windows 95 and later. Windows 10 Version 1607 (Anniversary Update), internal version 10.0.14393, released in 2016.

I think you are confusing two things here: "path length" and "file/directory name length", or as it is called by Jeremy Kuhne: "segment length" (see also https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/net-4-6-2-and-long-paths-on-windows-10)

![image](https://user-images.githubusercontent.com/344204/173227961-7419fded-8e09-4a9e-b34e-9320332f6804.png)

Before the update a path was limited to 260 characters. After the update this limit was raised, I believe to 2^16 (~32 000), however ILSpy treats it as "infinite" hence uses `int.MaxValue`.

However, the **segment length** is a filesystem limitation where a directory name or file name (NOT path) can only be up to 255 characters:

See also https://github.com/icsharpcode/ILSpy/pull/2567#issuecomment-986022914 

Sorry, for sounding harsh and rude, however, you are not the first person to report the file name truncation as being buggy and wrong, when in fact there is no good alternative, and I am a bit fed up with having to state the same facts and limitations over and over again. Sorry!

**Comment by dgrunwald** [comment] 2022-06-12 10:23
There are multiple types of long path support in Windows.
The ancient variant (afaik since Windows NT, but *not* on Windows 9x) requires the program to escape the paths using kernel path syntax `"\\?\c:\..."`. Note that the kernel path syntax also deactivates some other forms of normalization normally performed by Win32; which means the program will have to reimplement those. Also I believe there were some restrictions in .NET framework that prevented the use of kernel path syntax in .NET, but those might no longer apply to current .NET versions.

The new variant (since Windows 10 Version 1607) only requires setting the registry key, nothing else. The program can just use normal paths.

Since ILSpy doesn't use kernel path syntax, you will need to set the registry key to enable long path support. We didn't add the registry check for fun; users without the registry key set were reporting crashes due to the total path being too long, e.g. even on Windows 11: #2622

**Comment by avengerx** [comment] 2022-06-12 13:40
Ok, I got mixed up with the "segment" and "path" lengths. But still, 30 is too little for my use case. Windows 10, without 
`LongPathsEnabled`. There must be a more reasonable value for that limitation. In my case, the longest file name with extension was 47 characters, and it works like a charm. 

I don't know how 30 was decided upon but it simply is not realistic. Perhaps you should, instead limit the file name length to 255 or 260 -and- also check if the full path exceeds the limit before truncating it?

**Comment by avengerx** [comment] 2022-06-12 13:46
This statement from the very docs on the long path feature hints on a bit more limitation:
> _"When using an API to create a directory, the specified path cannot be so long that you cannot append an 8.3 file name (that is, the directory name cannot exceed MAX_PATH minus 12)."_

That could have been another reason 255 (neither 260) worked on Windows. It should instead be 260 - 12 = 248? I guess I can create a simple project and check that out.

**Comment by dgrunwald** [comment] 2022-06-12 15:41
The problem is that we only limit individual segments, but would need to also limit the full path.
But that gets complicated quickly (we can't just truncate the full path, we'd need to distribute the available space in the path to among the different segments).

But I think the upgrade to .NET 6 might save us here: Unlike .NET framework 4.x, the new .NET seems to internally convert normal paths to kernel paths: https://github.com/dotnet/corefx/pull/3001
Thus the registry key is no longer relevant and we could always use the long path support.

**Comment by avengerx** [comment] 2022-06-12 23:39
Okay, I gave it another try, changing it to validate the full path, and expand the output path to absolute when the class is instanced. I have tested its edge cases on Windows without long path support and it worked like a charm. This approach would help me split the embedded resources also in paths, albeit this is very prone to errors, if it proves problematic... I'll create an issue for the embedded resources if I can't find an already open one.

**Comment by avengerx** [comment] 2022-06-14 22:00
https://github.com/dotnet/runtime/blob/44b44501c76c46bd79ee52b7d9a9d8a4957fc85f/src/libraries/System.IO.FileSystem/tests/FileStream/ctor_options.Windows.cs#L89

This could be an interesting approach to get specific file system's path limit, once we already have the `TargetDirectory` resolved to a disk/mount point. (windows-specific). But this would still leave the issue with long paths not being able to be opened by the overall applications on the system.

**Closed** 2022-06-15 22:55 UTC
Labels: Bug, Decompiler
