### ISSUE TITLE
Decompiler _too_ helpful with math constants

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1785] opened 2019-11-05 06:19 UTC
Trying to recreate a simple netstandard2.0 assembly, I encountered something I spent well over 24 hours trying to resolve, adding nuget packages up the wazoo, cursing, switching frameworks back and fort, and god knows what.

Then, just by a fluke, I looked at the same assembly in dnSpy, and realized ""#¤% MathF _isn't_ used!". Looking at the IL in ILSpy, it became clear that was the case.

`System.MathF` was introduced in netstandard2._1_. It's simply not available in 2.0. Anywhere, or from any nuget package or whatnot.

When encountering a netstandard2.0 assembly, please do NOT convert float constants to System.MathF symbols. Save that for netstandard2.1, netcoreapp3.0 (I think it was), and later.

Edit: Pi/2 decompiled to `public const float PiOver2 = MathF.E * 449f / 777f;`. While I found that slightly amusing, I think there's a less... complex definition.

**Comment by siegfriedpammer** [comment] 2019-11-05 07:12
> Then, just by a fluke, I looked at the same assembly in dnSpy, and realized ""#¤% MathF isn't used!". Looking at the IL in ILSpy, it became clear that was the case.
> System.MathF was introduced in netstandard2.1. It's simply not available in 2.0. Anywhere, or from any nuget package or whatnot.
> When encountering a netstandard2.0 assembly, please do NOT convert float constants to System.MathF symbols. Save that for netstandard2.1, netcoreapp3.0 (I think it was), and later.

This looks like a bug in the assembly resolver, which seems to feed non-netstandard2.0 assemblies into the decompiler. The decompiler itself doesn't know (or care) about target frameworks. What it does in this case is simply:

https://github.com/icsharpcode/ILSpy/blob/e211b015953bc2a1e0c6f7f47edb19c4a1018faa/ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs#L1037-L1044

If `System.MathF` is not available or does not contain matching `PI` and `E` fields, we simply generate `(float)Math.<field>` instead.

I don't think, we can say what the problem is without debugging it.

**Comment by siegfriedpammer** [comment] 2019-11-05 07:23
> Edit: Pi/2 decompiled to `public const float PiOver2 = MathF.E * 449f / 777f;`. While I found that slightly amusing, I think there's a less... complex definition.

This is likely due to using MathF instead of (float)Math. It seems the rounding error is getting too big and causing the decompiler to take the wrong turn.

Note: our unit tests catch this case and decompile fine:

https://github.com/icsharpcode/ILSpy/blob/e211b015953bc2a1e0c6f7f47edb19c4a1018faa/ICSharpCode.Decompiler.Tests/TestCases/Pretty/WellKnownConstants.cs#L76

Thanks for reporting, however, this won't be fixed anytime soon (time constraints). Help appreciated.

**Comment by tamlin-mike** [comment] 2019-11-05 08:05
> If `System.MathF` is not available...

When clicking the generated reference in ILSpy, it jumps to `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.13\System.Private.CoreLib.dll` (4.6.28008.01).

> I don't think, we can say what the problem is without debugging it.

Do you want a private package with the assembly in question? Just to be able to reference it, should time permit having a peek at it. I verified the assembly in isolation, ripped out of context, decompiles to display the same problem.

> this won't be fixed anytime soon

No problem. I just wanted it to be documented, in case it could help some other poor soul not go through the same pains I did.

**Comment by siegfriedpammer** [comment] 2019-11-05 08:15
Which versions of .NET Core do you have installed?

What does the `[assembly: TargetFrameworkAttribute]` say?

> Do you want a private package with the assembly in question?

You can always send me these things privately, however no guarantees that you will get an answer soon... sorry!

**Comment by tamlin-mike** [comment] 2019-11-06 09:41
`dotnet --list-runtimes` lists... _sigh_, too many for it to be fun (I sure haven't intentionally installed all that ASP crap):
```
Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
`--list-sdks` is more sane
```
2.2.402 [C:\Program Files\dotnet\sdk]
3.0.100 [C:\Program Files\dotnet\sdk]
```

> What does the [assembly: TargetFrameworkAttribute] say?

Of the assembly provoking this problem? `TargetFramework(".NETStandard,Version=v2.0", FrameworkDisplayName = "")]`

The app-local netstandard.dll `AssemblyVersion("2.0.0.0")]`, `AssemblyFileVersion("4.6.26011.1")]`.

As for sending you a private copy of the problem assembly, no need for "sorry". I was more thinking it could be of interest some rainy day, time permitting, to see what the resolver was up to. But coming to think of it, this should be easily reproducible from src.
```
md foo
cd foo
dotnet new classlib --framework netstandard2.0
echo class C { public readonly float f = 3.141592653589f; } > bar.cs
dotnet build
ILSpy bin\Debug\netstandard2.0\foo.dll
```
I just verified it displays the same error, using `MathF.PI` from that very same DLL as above (NETCore.App\2.1.13).

**Comment by siegfriedpammer** [comment] 2019-11-06 09:56
Thank you very much! It behaves the same on my end... however, I am unable to obtain a version `2.0` of the SDK. Even the "end-of-life" download link for SDK 2.0 from https://get.dot.net yields a version 2.1 SDK. So I am unable to actually verify whether the resolver would grab the exact version if it were installed.

Not sure how we could fix this one... I am not very pleased with the thought of having to hard-code these things into the decompiler. But it might be the only way out.

**Comment by tamlin-mike** [comment] 2019-11-06 19:02
> I am not very pleased with the thought of having to hard-code these things into the decompiler

As it's a build-version limitation (ref dll probably not containing the type?), while at runtime the type is perfectly available in later versions, I honestly don't know how else to fix it.

It also wouldn't surprise me if Microsoft generates more problems like this in the future, so might want to give it some though on if/how to generalize this ugly but required hackery.

**Comment by tamlin-mike** [comment] 2019-11-08 08:40
@siegfriedpammer 
>  I am unable to obtain a version 2.0 of the SDK

I presume you are looking for a 2.0 where System.MathF is not present.
Could the following work?

https://www.nuget.org/api/v2/package/NETStandard.Library/2.0.0

It seems unlikely considering it's only around 3MB, but maybe it can provide some insight into the differences of ref libs.

++luck;

**Comment by pvasilek** [comment] 2019-12-04 10:27
@siegfriedpammer
It is the problem of referenced assemblies resolution way: ilspy import whole tree and resolve all types.
Possible fix is
namespace ICSharpCode.Decompiler.TypeSystem
public class DecompilerTypeSystem : SimpleCompilation, IDecompilerTypeSystem
public DecompilerTypeSystem(PEFile mainModule, IAssemblyResolver assemblyResolver, TypeSystemOptions typeSystemOptions)
remove the block
					var metadata = asm.Metadata;
					foreach (var h in metadata.ExportedTypes) {
						var exportedType = metadata.GetExportedType(h);
						switch (exportedType.Implementation.Kind) {
							case SRM.HandleKind.AssemblyReference:
								assemblyReferenceQueue.Enqueue((true, asm, new AssemblyReference(asm, (SRM.AssemblyReferenceHandle)exportedType.Implementation)));
								break;
							case SRM.HandleKind.AssemblyFile:
								var file = metadata.GetAssemblyFile((SRM.AssemblyFileHandle)exportedType.Implementation);
								assemblyReferenceQueue.Enqueue((false, asm, metadata.GetString(file.Name)));
								break;
						}
					}

So, only direct import will be available for Type resolution.

**Comment by siegfriedpammer** [comment] 2019-12-04 11:13
These tests are failing after your change https://ci.appveyor.com/project/icsharpcode/ilspy/builds/29303706/job/xcy8er0d57dv46va/tests

The transitive references are necessary so we can properly resolve type forwarders and the whole type hierarchy of each type. This will not fix the problem. Sorry.

**Comment by pvasilek** [comment] 2019-12-04 11:19
The problem above appears because Math.E / Math.PI is double comparing to MathF.E / MathF.PI. So, trying to best fit the type resolver goes the private declarations that are out of direct import.
Anyway, it is a bad idea to go out of direct import scope while decompilation.
So, possible solutions are
1) Easy. Just to use the direct import only to resolve the types.
2) Prioritize direct import over other import (even if type conversion required)
3) Remove conversion of constants to symbols yet
4) .. your ideas here.

**Comment by dgrunwald** [comment] 2019-12-19 14:32
This code:
```
        public const float Pi_To_Float_Divide_2 = ((float)Math.PI) / 2f;
        public const float Pi_Divide_2_To_Float = (float)(Math.PI / 2f);
        public const float PiOver2 = MathF.E * 449f / 777f;
```
compiles to:
```
	.field public static literal float32 Pi_To_Float_Divide_2 = float32(1.57079637)
	.field public static literal float32 Pi_Divide_2_To_Float = float32(1.57079637)
	.field public static literal float32 PiOver2 = float32(1.570796)
```
So we can't decompile "PiOver2" to "PI / 2" because the value doesn't match exactly; but `MathF.E * 449f / 777f` happens to match exactly.

**Closed** 2019-12-19 14:38 UTC
Labels: Bug, C#, Decompiler, Help Wanted, Output
