### ISSUE TITLE
ILSpy 8.0 Preview 3 doesn't start due to malfunctioning .NET dependency manager

### ISSUE THREAD

**Issue by ThePhantom6314** [icsharpcode/ILSpy#2884] opened 2023-01-13 13:28 UTC
### Steps to reproduce
1. Download the setup
2. Run the installer
3. Open the Program
4. Install .NET 6 when prompted
5.  Open the Program

### Error message shown
To run this application, you must install missing frameworks for .NET

Would you like to download it now
```
Copy and paste any error messages / relevant text and/or screenshot the incorrect behaviour.
```
![image](https://user-images.githubusercontent.com/120608561/212330708-483c1429-3ae7-4c50-a2fa-1f205533ddbd.png)

### Details
ILSpy 8.0 Preview 3

**Comment by christophwille** [comment] 2023-01-13 13:39
Duplicate of #2880 & #2870

**Comment by dgrunwald** [comment] 2023-01-13 16:06
The problem is that you need the .NET *Desktop* runtime 6.0.* for ILSpy, but clicking Yes download sends you to the non-Desktop version.
This is highly confusing, if we cannot somehow fix this I think we should *only* ship the self-contained deployment.

**Comment by christophwille** [comment] 2023-01-14 08:53
I don't think that not having .NET 6.0 on a machine is a widespread "problem" - do you really want everyone to pay the download penalty for selfcontained? Also, the installer builds fw-dependent, as well as the VSIXs.

**Comment by christophwille** [comment] 2023-01-14 09:11
I have been digging a bit in the dotnet repos:
* https://github.com/dotnet/runtime/issues/3850 with links to eg https://github.com/dotnet/runtime/issues/3816 (there are multiple)
* https://github.com/dotnet/runtime/pull/67564 this indicates to me that v7 already has an improved dialog (should we test?)

**Comment by christophwille** [comment] 2023-01-14 09:17
I have added a blurb to https://github.com/icsharpcode/ILSpy/releases/tag/v8.0-preview3: "IMPORTANT: If you don't have the .NET Desktop Runtime installed, the .NET bootstrapper (a dialog popping up when you try to run ILSpy) will link you to the .NET Runtime which supports only console apps! Please follow the above link and download the Desktop Runtime."

**Comment by christophwille** [comment] 2023-01-14 09:44
A stopgap measure (people not reading information on the download page) could also be https://github.com/Tyrrrz/DotnetRuntimeBootstrapper

**Comment by Artoria2e5** [comment] 2023-02-20 09:23
Huh, it somehow does download a "windowsdesktop-runtime-6.0.14-win-x64.exe" on my side. Did they fix it secretly?

**Closed** 2023-05-21 11:23 UTC
Labels: Bug, Duplicate
