### ISSUE TITLE
Decompilation stuck - does not cancel

### ISSUE THREAD

**Issue by LuisPerez89** [icsharpcode/ILSpy#2648] opened 2022-03-10 11:02 UTC
Hello,

Hope everything is fine with you.

I’m working with you library icsharpcode/ILSpy

I’m having some problems with a few packages where I tried to decompile their dll’s.

I cannot decompile a package Microsoft.Azure.Cosmos-3.23.0

This also happens with other packages, that would not be a problem if I could cancel(with CancellationToken) the task as it happens for the most part of the packages that dont decompile for reasons that I also dont know.

The cancellation token with cancelAfter work for some decompilation that does not finish in a few minutes, but not for this one Microsoft.Azure.Cosmos-3.23.0.

The decompilation of the dll’s of this package stay stuck.

One of the dll's is this one.
lib\\netstandard2.0\\Microsoft.Azure.Cosmos.Client.dll"

Could you help me?

I think the problem is related with the decompilation not triggering throwifcancellationrequested

Thank you

The settings that I’m using:

            var fileStream = new FileStream(assemblyFilePath, FileMode.Open, FileAccess.Read);
            module = new ICSharpCode.Decompiler.Metadata.PEFile(assemblyFilePath, fileStream, PEStreamOptions.PrefetchEntireImage);
            var resolver = new UniversalAssemblyResolver(assemblyFilePath, false, module.Reader.DetectTargetFrameworkId(), null, PEStreamOptions.PrefetchEntireImage);
            resolver.RemoveSearchDirectory(".");
            resolver.AddSearchDirectory(assemblyFilePath);

            var decompiler = new WholeProjectDecompiler(GetSettings(module), resolver, resolver, null)
            {
                MaxDegreeOfParallelism = 1,                
            };

            decompiler.DecompileProject(module, outputDirectory, ctsToken.Token);

    private static DecompilerSettings GetSettings(ICSharpCode.Decompiler.Metadata.PEFile module) =>
        new(LanguageVersion.Latest)
        {
            ThrowOnAssemblyResolveErrors = false,
            RemoveDeadCode = false,
            RemoveDeadStores = false,
            UseSdkStyleProjectFormat = WholeProjectDecompiler.CanUseSdkStyleProjectFormat(module)
        };
}

**Comment by LuisPerez89** [comment] 2022-03-10 11:22
I checked, from all dll's of this package Microsoft.Azure.Cosmos-3.23.0 , the only one that cannot be decompile and get stuck is this one lib\netstandard2.0\Microsoft.Azure.Cosmos.Client.dll

Note, there are also other packages that have dll's that I cant decompile but the cancellationToken can trigger to end the decompilation process, but I cant cancel the decompilation for the dll that I mentioned before.

**Comment by dgrunwald** [comment] 2022-04-09 13:35
Closing this as duplicate of #2652, which has more information.

**Closed by dgrunwald** 2022-04-09 13:35 UTC
Labels: Bug, Decompiler
