### ISSUE TITLE
he '`' character, hexadecimal value 0x60, cannot be included in a name

### ISSUE THREAD

**Issue by sergpolovinko** [icsharpcode/ILSpy#1445] opened 2019-03-11 15:49 UTC
ILSpy version 4.0.1.4530

When tryng to view .baml file embedded into obfuscated assembly, get an error.
Seems that in one of previous versions file is opened ok.

System.Xml.XmlException: The '`' character, hexadecimal value 0x60, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.LoadIntoDocument(PEFile module, IAssemblyResolver assemblyResolver, Stream stream, CancellationToken cancellationToken)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.LoadBaml(AvalonEditTextOutput output, CancellationToken cancellationToken)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.<>c__DisplayClass1_1.<View>b__2()

**Comment by siegfriedpammer** [comment] 2019-03-11 15:52
Without the assembly or baml file this will be hard to fix. Could you please provide the file?
Thank you very much!

**Comment by siegfriedpammer** [comment] 2019-04-04 06:51
Any update on this?

**Comment by sergpolovinko** [comment] 2019-04-04 08:04
Sorry for delay, the file is in attach
[va_debug.zip](https://github.com/icsharpcode/ILSpy/files/3042331/va_debug.zip)

**Comment by siegfriedpammer** [comment] 2019-04-04 08:48
Thank you for your response, however, I cannot reproduce the problem. Can you provide the full assembly and detailed instructions which resource you were trying to view? Thank you very much!

**Comment by siegfriedpammer** [comment] 2019-05-08 19:42
Closing because there was no further feedback. Works on my machine as expected.

**Closed by siegfriedpammer** 2019-05-08 19:42 UTC
Labels: XAML
