### ISSUE TITLE
Use nint everywhere if nint option is enabled

### ISSUE THREAD

**Issue by wwh1004** [icsharpcode/ILSpy#2259] opened 2021-01-02 08:21 UTC
ilspy sometimes uses nint and sometimes uses IntPtr. the decompiled code lookes a little strange.
``` cs
private unsafe static void Memset(nint source, int value, int length)
{
	if (value == 0)
	{
		int offset3 = 0;
		while (length >= sizeof(IntPtr))
		{
			*(IntPtr*)(void*)(IntPtr)(source + offset3) = (IntPtr)0;
			length -= sizeof(IntPtr);
			offset3 += sizeof(IntPtr);
		}
		for (; offset3 < length; offset3++)
		{
			*(sbyte*)(void*)(IntPtr)(source + offset3) = 0;
		}
	}
	else if (length > sizeof(IntPtr))
	{
		nint template = 0;
		*(byte*)(&template) = (byte)value;
		((byte*)(&template))[1] = (byte)value;
		*(short*)((byte*)(&template) + 2) = *(short*)(&template);
		if (sizeof(IntPtr) == 8)
		{
			*(int*)((byte*)(&template) + 4) = *(int*)(&template);
		}
		int offset2 = 0;
		while (length >= sizeof(IntPtr))
		{
			*(nint*)(void*)(IntPtr)(source + offset2) = template;
			length -= sizeof(IntPtr);
			offset2 += sizeof(IntPtr);
		}
		for (; offset2 < length; offset2++)
		{
			*(byte*)(void*)(IntPtr)(source + offset2) = (byte)value;
		}
	}
	else
	{
		for (int offset = 0; offset < length; offset++)
		{
			*(byte*)(void*)(IntPtr)(source + offset) = (byte)value;
		}
	}
}
```

**Comment by dgrunwald** [comment] 2021-01-02 20:31
Duplicate of #2258.

**Closed by dgrunwald** 2021-01-02 20:31 UTC
Labels: Bug
