### ISSUE TITLE
Issues with finding usages of a member implementing an interface member 

### ISSUE THREAD

**Issue by nvmkpk** [icsharpcode/ILSpy#1998] opened 2020-05-01 16:57 UTC
When a member is implementing an interface member, often we run into cases where it is only invoked via the interface member (very common in asp.net core). In this case ILSpy does not find any usages of it and requires us to analyze the interface member to find its possible usages. I would like to see an additional option under the member for `Implements` that would list the interface member it is implementing (or list it under `Exposed By` if it makes sense). That would make it little easier to find the usages.

**Comment by siegfriedpammer** [comment] 2020-05-01 17:03
Possible duplicate of #648

**Comment by nvmkpk** [comment] 2020-05-01 17:14
Yes, I created new one because that issue is closed and I included a suggestion for better implementation/fix than the workaround mentioned there.

**Closed** 2020-06-03 08:25 UTC
Labels: Analyzer, Enhancement, Help Wanted

**Comment by nvmkpk** [comment] 2020-06-03 16:36
It is nice to see this implementation. Would have been even nicer if overridden members are also shown under 'Overrides' (if not under 'Implements').
