### ISSUE TITLE
Add support for .netmodule(s)

### ISSUE THREAD

**Issue by Meai1** [icsharpcode/ILSpy#494] opened 2014-10-10 11:33 UTC
Currently they are shown like this in the ui:

![netmodule](https://cloud.githubusercontent.com/assets/1112157/4591724/287d8348-5071-11e4-9f34-d7a16ffac334.PNG)

I understand that not all of these modules may be parsable, but some are and in c# code Assembly.GetTypes() returns all of the classes from all .netmodules, so I think it's a necessary feature to mirror what we get in normal code.
In the screenshot the myclass.netmodule contains normal c# code and namespaces.

**Comment by dgrunwald** [comment] 2018-06-02 15:31
Duplicate of #221

**Closed by dgrunwald** 2018-06-02 15:31 UTC
