### ISSUE TITLE
Cannot disassemble assemblies created through Reflection.Emit

### ISSUE THREAD

**Issue by TheEvilDev** [icsharpcode/ILSpy#356] opened 2012-08-20 01:04 UTC
I'm currently working on a project that uses Reflection.Emit to spit out dynamic proxy assemblies. This code is incredibly hard to debug, so if I could disassemble the output to make sure the dynamic assemblies/types are being generated the way I expect them to is a must. Unfortunately I'm getting the following error when I try to load a dynamic assembly:

System.ArgumentException: Value does not fall within the expected range.
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly()
   at System.Threading.Tasks.Task`1.InvokeFuture(Object futureAsObj)
   at System.Threading.Tasks.Task.Execute()

**Comment by siegfriedpammer** [comment] 2017-10-03 13:00
It's hard to see what the problem is here, because ILSpy should be fine loading assemblies generated by Reflection.Emit and written to disk. Dynamic assemblies are somewhat different. No idea how you even managed loading a dynamic assembly in ILSpy. Therefore I'll close this. If somebody has a similar issue, please add an example of how you load the assembly in ILSpy and provide an assembly for us to debug. Thank you!

**Closed by siegfriedpammer** 2017-10-03 13:00 UTC
Labels: Bug, Decompiler
