### ISSUE TITLE
Could not find reference: System.Buffers, Version=4.0.2.0

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2051] opened 2020-06-27 09:32 UTC
### Steps to reproduce
1. Click on References in left tree view
2. all dlls are resolved except one
3. 

start of references text:
```
// Detected Target-Framework-Id: .NETFramework,Version=v4.7.2

// Referenced assemblies (in metadata order):
// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

.........
```

### Error message shown

```
// System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
	// Assembly reference loading information:
	// There were some problems during assembly reference load, see below for more information!
	// Error: Could not find reference: System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
```

### Details
ILSpy version 6.0.0.5800-preview4

The possible issue might be mentioned here:
https://github.com/dotnet/runtime/issues/1830

and here is a set of my frameworks installed:

![image](https://user-images.githubusercontent.com/765343/85919257-6a742300-b872-11ea-843c-b73c3f1ab8ed.png)

After exporting to project and trying to open up got this error:
![image](https://user-images.githubusercontent.com/765343/85919527-75c84e00-b874-11ea-9dbb-fd1adb6cecfd.png)

**Comment by siegfriedpammer** [comment] 2020-07-08 14:08
How was the binary created? As far as I can tell, System.Buffers is a nuget package and not part of the GAC.

**Comment by siegfriedpammer** [comment] 2022-04-14 13:21
Closing - no feedback; cannot reproduce

**Closed by siegfriedpammer** 2022-04-14 13:21 UTC
Labels: Bug
