### ISSUE TITLE
ILSpy should hide/transform references to compiler-generated backing fields used in auto properties regardless of their name

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1109] opened 2018-04-02 15:26 UTC
this demo will show "ok"
but the decompilation code will show nothing.

[mytest1.zip](https://github.com/icsharpcode/ILSpy/files/1868440/mytest1.zip)

**Comment by siegfriedpammer** [comment] 2018-04-07 19:29
Could you post the original C# code and the compiler used to generate the assembly? Thank you very much!

**Comment by CreateAndInject** [comment] 2018-04-08 01:33
There's no original C# code, because I modified it by reflexil.

**Comment by siegfriedpammer** [comment] 2018-04-08 07:47
Then the problem is that you did not follow the usual naming convention for compiler-generated fields. The compiler uses `<PropertyName>k__BackingField` for backing fields. ILSpy is very defensive and does not replace assignments to other fields.

Currently I won't have time to fix this. Maybe in the next major release...

**Comment by siegfriedpammer** [comment] 2018-05-21 16:39
We won't fix this, because it is a niche problem. If you want the decompiler to do it's job properly, either do not modify the assembly or follow the usual naming convention as noted above.

**Closed by siegfriedpammer** 2018-05-21 16:39 UTC
Labels: Won't Fix
