### ISSUE TITLE
Error saving *.baml resources in project - corrupted filenames

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2565] opened 2021-11-30 12:52 UTC
### Steps to reproduce
1. Get an assembly that has .g.resources resource that has some *.baml underneath
2. Save it as project (File -> Save code)
3. The project saved without errors, but filenames of some saved resources are corrupted.

I"ve seen this issue already on a couple of assemblies, so I made a conclusion this is a generic issue.

### Error message shown

Some of the saved resources were successfully decompiled and saved as .xaml files
but rest of items have got 2 errors
1) it stayed as .baml (binary xaml) - was not decompiled for some reason
2) these bamls had got currupted file names - some had got eaten file extention, some  - missing full extension + end of filename itself

here is an example of the strange issue (picture of saved project out from ILSpy):

![image](https://user-images.githubusercontent.com/765343/144050092-8216a7cd-ca8a-492d-8a94-86e863b103c9.png)

"+" means all fine - baml -> xaml done!
"?" - wrongly saved resources  (instead of xaml we have got baml) and as you see - some names got corrupted (trimmed)

### Details
ILSpy version 7.2.0.6772-preview3
.NET version 4.8.3928.0

**Comment by greenozon** [comment] 2021-11-30 12:57
There is yet another issue with resources, maybe it worth to open up another ticket?

in 2 words - if baml in resource section having name  like a\b\c.baml
then for some reason the decompiled directory wil have  file names in project root a-b-c.xaml
instead of a\b\c.xaml

In my opinion it should be a\b\c.xaml...

**Comment by siegfriedpammer** [comment] 2021-12-02 10:55
I can reproduce the issue described in the second comment, but not the first. Would you be able to provide an assembly? Thank you!

**Comment by greenozon** [comment] 2021-12-02 11:44
sent by PM

**Comment by siegfriedpammer** [comment] 2021-12-02 12:57
still cannot reproduce... only XAML files are produced and no baml files.

**Comment by dgrunwald** [comment] 2021-12-02 13:33
Likely related to the paths getting truncated by the fix for #2038?

**Comment by siegfriedpammer** [comment] 2021-12-02 18:33
Yes, that is the cause... confirmed using my test vm.

**Comment by greenozon** [comment] 2021-12-02 18:44
I"ve debugged the case on my system
the root reason is inside routine named

static string CleanUpFileName(string text, bool separateAtDots)

located inside namespace ICSharpCode.Decompiler.CSharp.ProjectDecompiler

it has some strange value maxSegmentLength  which is just 30 symbols for file name..
if that value was hit, the filenames are being trimmed, thats why I'm getting trimmed bamls instead of xamls

**Comment by greenozon** [comment] 2021-12-07 20:48
@siegfriedpammer 
some updates:
"ILSpy 7.2.0.6780-filename-sanitizer-preview3 (debug)"  build produces expected results (no broken names, + it produces subdirs in project as it was for ages

latest build - "ILSpy 7.2.0.6787-preview3 (debug)"  is not sane IMHO
reasons:
- again broken names - this time directories?!
- why not creating subdirs anymore? instead using "." as contanation for subdirs... very unusual solution, what is the reasoning for that approach? I've never seen in any live .net project such project structures...

**Comment by siegfriedpammer** [comment] 2021-12-07 20:55
> @siegfriedpammer some updates: "ILSpy 7.2.0.6780-filename-sanitizer-preview3 (debug)" build produces expected results (no broken names, + it produces subdirs in project as it was for ages
> 
> latest build - "ILSpy 7.2.0.6787-preview3 (debug)" is not sane IMHO reasons:
> 
> * again broken names - this time directories?!

Could you explain what the problem is exactly?

> * why not creating subdirs anymore? instead using "." as contanation for subdirs... very unusual solution, what is the reasoning for that approach? I've never seen in any live .net project such project structures...

There is a new option (it was added in response to #2330 - default is false, as the development team prefers the non-nested namespace directories)
![image](https://user-images.githubusercontent.com/344204/145104394-2d713a00-4ae7-42fb-830e-e099ade057db.png)

**Comment by greenozon** [comment] 2021-12-07 21:06
oh, great if this change is under feature flag! thanks for letting me know!

the issue I've mentioend is that  these modern dirs like
dirA.driB.dirC  now get trimmed like 
dirA.dirB.di

thats bad example, in my case 5 dirs with dots were trimmed exactly to 30 symbols + 1 file also to 30 symbols...
as far as I see the trimming happens only on those items which are contatenated by "."

regular files might be much longer in name - no trims.

**Comment by greenozon** [comment] 2021-12-07 21:27
OK, tried latest build - "ILSpy 7.2.0.6787-preview3 (debug)"  once again with "use nested directories" checkbox ON
the subdirs issue gone away,
but the file was not put into subdirs, but instead left as  dirA.dirB.dirC.fliename_corrupted
under corrupted I mean a couple of chars were eaten
filelen = 30 chars
file type - resx but not decompiled to text resx, but left as binary one...

**Comment by siegfriedpammer** [comment] 2021-12-08 01:21
Sorry for making all this so complicated, but could you provide an example binary for me to quickly test and reproduce this behavior? Thanks!

**Comment by greenozon** [comment] 2021-12-08 12:44
yeah, sent privately

**Comment by siegfriedpammer** [comment] 2021-12-08 22:32
Should be fixed now. @greenozon Please close this issue if you think this is fixed, otherwise report any further problems. Thanks!

**Comment by greenozon** [comment] 2021-12-09 07:41
@siegfriedpammer 
**THANKS a lot**
this was a long and hard nut!
but now all is fine and we could go celebrate great holidays soon!

**Closed** 2021-12-09 10:01 UTC
Labels: Bug
