### ISSUE TITLE
Does not work with .net core assemblies

### ISSUE THREAD

**Issue by matafonoff** [icsharpcode/ILSpy#789] opened 2017-01-13 10:38 UTC
There's an exception if I'm trying to decompile asp.net core assembly

System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at ICSharpCode.ILSpy.LoadedAssembly.LoadSymbols(ModuleDefinition module)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by VahidN** [comment] 2017-01-13 11:07
It's duplicate of https://github.com/icsharpcode/ILSpy/issues/779

**Comment by AArnott** [comment] 2017-03-10 16:45
I agree it's a dupe, but the dupe has been closed with an unrelated fix. 

I don't think CoreCLR assemblies have changed from desktop assemblies. Rather: the PDB that is generated (by default) for .NET Core projects are the new "portable" variety, and this exception is thrown from the PDB reader. So I think it's a (significant) change to support [the new portable PDB format](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/portable_pdb.md).

**Comment by memark** [comment] 2017-05-16 14:49
The fix (deleting the .PDB) works for me for any .NET Core assembly.

Did you try it @AArnott?

**Comment by AArnott** [comment] 2017-05-16 16:38
Yes. It works for me too. I mentioned that here: https://github.com/icsharpcode/ILSpy/issues/779#issuecomment-285719981

**Comment by airbreather** [comment] 2017-05-23 12:56
https://github.com/airbreather/ILSpy/tree/github-789

I have no idea what I'm doing (thus no pull request just yet), but running it in VS2017 makes it feel like the problem is fixed.  26 tests fail, but debugging through them it's always just at the `File.Delete` calls because apparently something's keeping the files open (so I'm going to ignore those).

I saw the `newdecompiler` branch but that's a lot bigger of a fix than this, so I thought it might be worth putting this out there.

Semi-unrelated changes are from a VS2017 "one-way-upgrade" on `ILSpy.AddIn`.

**Comment by dungtm007** [comment] 2017-07-22 01:33
Thanks @memark 
It works for me ;)

**Comment by dgrunwald** [comment] 2017-09-14 19:12
This was likely fixed in the new decompiler engine (which just landed on the master branch).

**Closed by dgrunwald** 2017-09-14 19:12 UTC
