### ISSUE TITLE
ILSpy crash when searching for a method

### ISSUE THREAD

**Issue by Oberndorfer** [icsharpcode/ILSpy#2293] opened 2021-02-04 09:23 UTC
### Steps to reproduce
1. Open Search Pane
2. Choose "Search for: Method"
3. Enter 3 or more characters

### Error message shown
Sorry we crashed.
NullReferenceException...

![ILSpy Crash](https://user-images.githubusercontent.com/40287684/106871267-5c249a00-66d2-11eb-845c-8df535d87764.png)

### Details
ILSpy version 6.2.1.6137

**Comment by siegfriedpammer** [comment] 2021-02-04 10:42
Possible duplicate of #2241. Could you try one of the 7.0 previews?

**Comment by Oberndorfer** [comment] 2021-02-04 10:46
Yes, it is resolved with ILSpy version 7.0.0.6291-preview2

**Closed** 2021-02-04 10:45 UTC
Labels: Bug

**Comment by siegfriedpammer** [comment] 2021-02-04 10:51
Duplicate of #2241
