### ISSUE TITLE
Incorrect decompilation (C#) "is null" (== null) and "is not null" (!= null) for Nullable types. Wrong using ! operator.

### ISSUE THREAD

**Issue by ElbrusCloud** [icsharpcode/ILSpy#3286] opened 2024-09-23 17:29 UTC
For `is null` and `== null` missing ! operator in decompiled code.
### Input code
```c#
int? a = 1;
if (a is null)
{
}
```
### Expected  output
```c#
if (!new int?(1).HasValue)
{
}
```
### Erroneous output
```c#
if (new int?(1).HasValue)
{
}
```
### Screen
![image](https://github.com/user-attachments/assets/23e539c9-79c7-4390-bb2c-3527204a9f61)

For `is not null` and `!= null` unnecessary ! operator in decompiled code.
### Input code
```c#
int? a = 1;
if (a is not null)
{
}
```
### Expected  output
```c#
if (new int?(1).HasValue)
{
}
```
### Erroneous output
```c#
if (!new int?(1).HasValue)
{
}
```

### Details
* Product in use: VS extension
* Version in use: 8.2.0.7535
* Similar issues: #3181

**Comment by siegfriedpammer** [comment] 2024-09-29 12:08
Duplicate of #1687

See https://github.com/icsharpcode/ILSpy/issues/1687#issuecomment-527400334
> If you have an empty if at the end of the method, the then and else branches are indistinguishable, so the condition being negated is not a bug.

**Comment by siegfriedpammer** [comment] 2024-10-14 13:07
Working as expected - not a bug. Closing.

**Closed by siegfriedpammer** 2024-10-14 13:07 UTC
Labels: Bug, Decompiler
