### ISSUE TITLE
ThrowKeyNotFoundException in AwaitInFinallyTransform

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#2598] opened 2022-01-04 08:40 UTC
### Input code
```c#
async Task Test(bool a)
{
	while (true)
	{
		try
		{
			await using var s = new MemoryStream();
			Console.WriteLine("do something");
			if (a)
				break;
			Console.WriteLine("CODE 1");
		}
		catch
		{
			await Task.Delay(1000);
			continue;
		}
		Console.WriteLine("CODE 2");
	}
	Console.WriteLine("END");
}
```

### Erroneous output
7.2.0.6820-preview4: KeyNotFoundException
```c#
System.Collections.Generic.KeyNotFoundException: 
   at System.ThrowHelper.ThrowKeyNotFoundException() in offset 5
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key) in offset 30
   at ICSharpCode.Decompiler.IL.ControlFlow.ControlFlowGraph.GetNode(Block block) in ControlFlowGraph.cs:line 159
   at ICSharpCode.Decompiler.IL.ControlFlow.AwaitInFinallyTransform.<Run>g__MoveDominatedBlocksToContainer|0_0(Block newEntryPoint, Block endBlock, ControlFlowGraph graph, BlockContainer targetContainer, List`1 removedBlocks, <>c__DisplayClass0_0&) in AwaitInFinallyTransform.cs:line 256
   at ICSharpCode.Decompiler.IL.ControlFlow.AwaitInFinallyTransform.Run(ILFunction function, ILTransformContext context) in AwaitInFinallyTransform.cs:line 191
   at ICSharpCode.Decompiler.IL.ControlFlow.AsyncAwaitDecompiler.Run(ILFunction function, ILTransformContext context) in AsyncAwaitDecompiler.cs:line 162
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1553
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1590
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1465
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions) in CSharpDecompiler.cs:line 995
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions) in CSharpDecompiler.cs:line 952
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(IMethod method, ITextOutput output, DecompilationOptions options) in offset 246
   at ICSharpCode.ILSpy.TreeNodes.MethodTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options) in offset 15
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in offset 143
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass51_0.<DecompileAsync>b__0() in offset 38
```
7.0.0.6372-preview3 and old: `CODE 2` is missing
```cs
async Task Test(bool a)
{
	while (true)
	{
		try
		{
			await using (new MemoryStream())
			{
				Console.WriteLine("do something");
				if (!a)
				{
					Console.WriteLine("CODE 1");
				}
			}
		}
		catch
		{
			await Task.Delay(1000);
			continue;
		}
		break;
	}
	Console.WriteLine("END");
}
```

### Details
* Product in use: ILSpy 
* Version in use: 7.2.0.6820-preview4

**Comment by siegfriedpammer** [comment] 2022-04-18 20:42
Cannot reproduce... most likely fixed by 84c15bb24f7ba144eda8e83c49446d7742aca8dc

**Closed by siegfriedpammer** 2022-04-18 20:42 UTC
Labels: Bug, Decompiler
