### ISSUE TITLE
[Bug report] Crash at startup

### ISSUE THREAD

**Issue by mdziczkowski** [icsharpcode/ILSpy#2607] opened 2022-01-10 21:26 UTC
Hello. I had just downloaded ILSpy for Linux and it has crashed short after starting up, without I was able to do anything in it. I attach the crash log.
[ilspy.log](https://github.com/icsharpcode/ILSpy/files/7841961/ilspy.log)

### Enviroment:

* System: debian 11
* ILSpy version: 7.2 Preview 3

**Comment by riQQ** [comment] 2022-01-10 21:43
Duplicate of https://github.com/icsharpcode/AvaloniaILSpy/issues/96

**Comment by siegfriedpammer** [comment] 2022-01-10 21:56
This is the wrong repo. We only deal with bug reports related to the ILSpy WPF UI for Windows or ILSpyCmd Console or the core decompiler engine ICSharpCode.Decompiler nuget package. For the Avalonia x-plat UI go to https://github.com/icsharpcode/AvaloniaILSpy Thanks!

**Closed by siegfriedpammer** 2022-01-10 21:56 UTC
Labels: Bug
