### ISSUE TITLE
Assert at ICSharpCode.Decompiler.IL.DeconstructInstruction.<CheckInvariant>g__ValidatePattern|30_0(MatchInstruction inst, <>c__DisplayClass30_0&) in DeconstructInstruction.cs:line 314

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2531] opened 2021-10-30 18:31 UTC
### Steps to reproduce
1. Save project
2. 
3. 

### Error message shown

```
Error decompiling @06000630 Microsoft.CodeAnalysis.ProjectDependencyGraph.RemoveItemsWithEmptyValues
in assembly "C:\IL_errs\Microsoft.CodeAnalysis.Workspaces.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 380
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message) in offset 9
   at System.Diagnostics.TraceInternal.Fail(String message) in offset 55
   at System.Diagnostics.Debug.Assert(Boolean condition) in offset 6
   at ICSharpCode.Decompiler.IL.DeconstructInstruction.<CheckInvariant>g__ValidatePattern|30_0(MatchInstruction inst, <>c__DisplayClass30_0&) in DeconstructInstruction.cs:line 314
   at ICSharpCode.Decompiler.IL.DeconstructInstruction.CheckInvariant(ILPhase phase) in DeconstructInstruction.cs:line 282
   at ICSharpCode.Decompiler.IL.Transforms.StatementTransform.Run(Block block, BlockTransformContext context) in StatementTransform.cs:line 139
   at ICSharpCode.Decompiler.IL.Block.RunTransforms(IEnumerable`1 transforms, BlockTransformContext context) in Block.cs:line 318
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 118
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.Run(ILFunction function, ILTransformContext context) in BlockTransform.cs:line 90
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1564
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1601
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1479
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1309
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in CSharpDecompiler.cs:line 574
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 894
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in WholeProjectDecompiler.cs:line 239
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1() in offset 713
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) in offset 6
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>) in offset 134

```

### Expected output
```
		private static ImmutableDictionary<ProjectId, ImmutableHashSet<ProjectId>> RemoveItemsWithEmptyValues(ImmutableDictionary<ProjectId, ImmutableHashSet<ProjectId>> map)
		{
			ImmutableDictionary<ProjectId, ImmutableHashSet<ProjectId>>.Builder builder = null;
			foreach (KeyValuePair<ProjectId, ImmutableHashSet<ProjectId>> keyValuePair in map)
			{
				ProjectId projectId;
				ImmutableHashSet<ProjectId> immutableHashSet;
				keyValuePair.Deconstruct(out projectId, out immutableHashSet);
				ProjectId projectId2 = projectId;
				if (immutableHashSet.IsEmpty)
				{
					if (builder == null)
					{
						builder = map.ToBuilder();
					}
					builder.Remove(projectId2);
				}
			}
			return ((builder != null) ? builder.ToImmutable() : null) ?? map;
		}
```

### Details
ILSpy version 7.2.0.6689-preview1
.NET version 4.8.3928.0

[Microsoft.CodeAnalysis.Workspaces.zip](https://github.com/icsharpcode/ILSpy/files/7447410/Microsoft.CodeAnalysis.Workspaces.zip)

**Comment by siegfriedpammer** [comment] 2021-11-07 18:30
Duplicate of #2378

**Closed by siegfriedpammer** 2021-11-07 18:30 UTC
Labels: Bug
