### ISSUE TITLE
VSIX crashes right after install

### ISSUE THREAD

**Issue by cjmairair** [icsharpcode/ILSpy#1481] opened 2019-04-10 15:21 UTC
Tools > ILSpy > Sorry, we crashed.

NullReferenceException

in Languages.Initialize()

**Comment by siegfriedpammer** [comment] 2019-04-10 16:16
Which version of Visual Studio are you using? Which version of the ILSpy extension did you install? Thank you very much!

**Comment by cjmairair** [comment] 2019-04-10 17:33
VS2017 Enterprise
ILSpy - the latest, I just downloaded it today. I think it's 5.0.1

**Comment by christophwille** [comment] 2019-04-11 04:47
We need the exact version of VS (15.x.y)

**Comment by siegfriedpammer** [comment] 2019-04-11 07:58
I cannot reproduce this. I tried uninstalling/installing the extension again, but no success. The problem is that there is some version problem with some of the libraries (sorry, don't remember which) and thus the initialization of MEF fails. Leading to a NRE later on.

However it should fail on every machine.

**Comment by cjmairair** [comment] 2019-04-11 16:01
VS 15.9.11

**Comment by siegfriedpammer** [comment] 2019-04-12 13:28
Could you try the VSIX package from [here](https://ci.appveyor.com/api/projects/icsharpcode/ilspy/artifacts/ILSpy.AddIn/bin/Release/net462/ILSpy.AddIn.vsix?branch=master&job=Configuration%3A+Release)? Thank you!

**Comment by siegfriedpammer** [comment] 2019-05-09 06:57
Could you try the VSIX package from [here](https://ci.appveyor.com/api/projects/icsharpcode/ilspy/artifacts/ILSpy.AddIn/bin/Release/net462/ILSpy.AddIn.vsix?branch=master&job=Configuration%3A+Release)? Thank you!

I improved error handling in case of start-up errors.

**Comment by christophwille** [comment] 2019-07-08 12:49
@YasminEndusa @cjmairair could you please try the 5.0 preview3 pre-release? (see https://github.com/icsharpcode/ILSpy/releases/tag/v5.0-preview3)

**Comment by christophwille** [comment] 2019-07-13 08:53
No feedback, closing.

**Closed by christophwille** 2019-07-13 08:53 UTC
