### ISSUE TITLE
Keeps crashing Visual Studio 2019

### ISSUE THREAD

**Issue by wiz0u** [icsharpcode/ILSpy#1706] opened 2019-09-21 19:41 UTC
I used ILSpy extension for VS2017 happily for a while now.
Recently I switched to VS2019 (Community) and ILSpy extension keeps crashing the whole IDE most of the times I use it (but sometimes it work)

According to Event Viewer, the error is this:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotImplementedException
   at EnvDTE.Project.get_FileName()
   at ICSharpCode.ILSpy.AddIn.Commands.ILSpyCommand.FindProject(System.Collections.Generic.IEnumerable`1<EnvDTE.Project>, System.String)
   at ICSharpCode.ILSpy.AddIn.Commands.OpenCodeItemCommand+<OnExecute>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by siegfriedpammer** [comment] 2019-09-22 05:48
Which kind of project and code did you try to use the AddIn with?

The NotImplementedException comes from VS, so it would be interesting to know which kind of project produces it.

Thank you!

**Comment by wiz0u** [comment] 2019-09-23 00:57
Classic C# csproj (not the new simplified ones). NET 4.7.2 framework not Core/standard

**Comment by wiz0u** [comment] 2019-09-23 01:00
Some of my csproj/sln may however still bear markers that they have been authored under VS2017 as some of them have not been modified since I migrated to VS2019 (if that could be the issue)

**Comment by christophwille** [comment] 2019-09-23 05:03
Would you be able to strip down one of those project files to a sample (with a simple demo C# class in it) that still exhibits the behaviour?

**Comment by wiz0u** [comment] 2019-09-23 23:10
It seems to be related to having an unloaded project.

Using the attached solution zip [CrashILSpy.zip](https://github.com/icsharpcode/ILSpy/files/3644484/CrashILSpy.zip) : 
- Open Test.sln. (There is a missing/unloaded project "Unloaded")
- Open MainForm.cs code from WFApp
- Place caret on "Form"
- Wait for background loading/parsing to be complete
- Right-click and select "Open code in ILSpy"
- BOOM! Visual Studio crashes (and sometimes restarts itself)
![image](https://user-images.githubusercontent.com/11647984/65469463-d8189c00-de67-11e9-8bf8-8238b1eb22fd.png)

**Comment by christophwille** [comment] 2019-09-24 05:33
I see the unloaded project as described, however, when following the procedure "Open code in ILSpy" does exactly nothing. @siegfriedpammer @Rpinski could you please try as well?

My setup: VS 16.3 RTM and ILSpy 6.0.0.5171 (yep, I did some tests locally, but it should be identical to the 5.0 RTM version)

**Comment by wiz0u** [comment] 2019-09-24 08:53
This ticket seems related:
https://developercommunity.visualstudio.com/content/problem/383952/envdteprojectfilename-throws-notimplementedexcepti.html

**Comment by wiz0u** [comment] 2019-09-24 09:39
> does exactly nothing
Shouldn't it open ILSpy on the System.WinForms.Form class?

**Comment by Rpinski** [comment] 2019-09-24 21:55
I was able to reproduce it here with your test project (thank you!). Seems to be exactly the issue with `EnvDte.Project.FileName` you have mentioned. I think we just need to work around it with a null check.

**Comment by siegfriedpammer** [comment] 2019-09-25 06:43
> I think we just need to work around it with a null check.

Isn't it throwing a NotImplementedException?

**Comment by Rpinski** [comment] 2019-09-25 06:45
You're right, it was late yesterday...
Of course we'll need to catch the exception, apparently this is not intended to be fixed in VS soon.

**Comment by siegfriedpammer** [comment] 2019-09-25 07:12
@Rpinski Once you are done, would you be able to cherry-pick the fix to https://github.com/icsharpcode/ILSpy/tree/5.0.x ? If not, I can do that for you.

**Comment by Rpinski** [comment] 2019-09-25 07:38
No problem, I'll do that.

**Closed** 2019-09-25 19:43 UTC
Labels: VS Extension
